### PR TITLE
Fix cast to `regclass` to be aware of the current search_path

### LINKED ISSUE #12586: 'relname'::regclass returns different result with pg_class.oid
### CrateDB version

4.8.1

### CrateDB setup information

_No response_

### Steps to Reproduce

```
CREATE TABLE persons (
    x int
);
```

PG13:
```
select 
  '"persons"'::regclass::integer as oid_from_relname, 
  oid
from pg_class where relname ='persons';



oid_from_relname | oid
--                             | --
16385                     | 16385

```

CrateDB
```
select  
      '"persons"'::regclass::integer oid_from_relname,  
        oid 
        from pg_class where relname ='persons';                                                                                                                                                                                         
+------------------+------------+
| oid_from_relname |        oid |
+------------------+------------+
|       1736852651 | 1726373441 |
+------------------+------------+
```

### Expected Result

oid_from_relname produces same result as pg_class.oid (like PG does)
https://www.db-fiddle.com/f/w7inAFr7v1nFDp5xc9QiQS/3

### Actual Result

 1736852651 != 1726373441

### PR DESCRIPTION
**Pull request by seut**
## Summary of the changes / Why this improves CrateDB

While casting to `regclass`, the used regclass type must be
constructed using the current defined `search_path` to create
the correct relation OID.

~The Scalar.compile() functionality is used to create new
cast function instances with the adjusted regclass type.~

Fixes #12586.
Closes https://github.com/crate/crate/issues/10735

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

File: server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java [hunk 1]
```diff
@@ -238,6 +239,12 @@ private Symbol normalizeFunction(Function function, TransactionContext context)
                 context.sessionSettings().searchPath()
             );
             assert implementation != null : "Function implementation not found using full qualified lookup: " + function;
+
+            // Some scalar implementation may change their semantic by compile as session settings are passed it.
+            if (implementation instanceof Scalar scalar) {
+                implementation = scalar.compile(function.arguments(), context.sessionSettings(), nodeCtx.userLookup());
```
Comment (seut) [inline server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java:245]: Calling `compile` on normalization currently causes some tests to fail as some scalars do not take care of `NULL` literals inside their `compile` methods.
This would be required if we want to adjust the return type of the cast functions once by creating a new instance.
The only drawback I see is that it may not conceptually fit and successful normalization results in a literal so compilation in order to avoid repeated expensive logic on every row won't count.

Another option would be to adjust the return type additionally inside the casts `normalize` method.
The drawback here would be a bit of duplicated code.

@mfussenegger wdyt?

Comment (mfussenegger) [reply server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java:245]: I'm thinking that `evaluate` should probably have this additional logic as well. `compile` should be a pure performance optimization with no semantics change.

Comment (seut) [reply server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java:245]: > I'm thinking that evaluate should probably have this additional logic as well. 

In this case we'd have to
a) modify the used type for casting on every row (which has probably performance impacts)
b) mutate the `returnType` of the instance.

Comment (mfussenegger) [reply server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java:245]: Isn't it possible to still have the `compile` to avoid the per row performance implications, but have `evaluate` / `normalizeSymbol` do the check too?

Or given that the `returnType` is available at construction time, we could have two different cast implementations without using compile for it?

Comment (seut) [reply server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java:245]: > Isn't it possible to still have the compile to avoid the per row performance implications, but have evaluate / normalizeSymbol do the check too?

Doing it on `compile` + `normalizeSymbol` would work, but why then also on `evaluate` (as evaluation is called per row)? 

> Or given that the returnType is available at construction time, we could have two different cast implementations without using compile for it?

Maybe I misunderstand your point here, but that is exactly the root cause. The `search_path` of the session is currently not passed-in to the constructors on function resolving. Do you argue that this should be changed (which could be a solution indeed)?

Comment (mfussenegger) [reply server/src/main/java/io/crate/expression/eval/EvaluatingNormalizer.java:245]: > Doing it on compile + normalizeSymbol would work, but why then also on evaluate (as evaluation is called per row)?

Because both `compile` and `normalizeSymbol` are so far kinda optional. I think `SymbolEvaluator` for example doesn't call them.

> Maybe I misunderstand your point here, but that is exactly the root cause. The search_path of the session is currently not passed-in to the constructors on function resolving. Do you argue that this should be changed (which could be a solution indeed)?

It wasn't what I had in mind but I was confused by the second constructor that's called from compile. Maybe it would be an option. Or maybe as alternative we specialize the regclass cast case completely without going through the generic cast? Not sure if that works better or is worse.

I also just saw that this adds the `currentSchema` to the `Regclass` type, but doesn't stream the value (so data type serialization would also change semantics). I think we've to address that too somehow.

File: server/src/test/java/io/crate/types/TimeTZTypeTest.java [hunk 2]
```diff
@@ -41,69 +46,69 @@ private static org.hamcrest.Matcher<TimeTZ> isTZ(long value, int zoneOffset) {
...
-        assertThat(TimeTZType.INSTANCE.implicitCast("01:00:00     GMT"), isTZ(3600000000L));
-        assertThat(TimeTZType.INSTANCE.implicitCast("01:00:00  Z"), isTZ(3600000000L));
-        assertThat(TimeTZType.INSTANCE.implicitCast("01:00:00 +00"), isTZ(3600000000L));
-        assertThat(TimeTZType.INSTANCE.implicitCast("04:00:00-03:00"), isTZ(14400000000L, -10800));
-        assertThat(TimeTZType.INSTANCE.implicitCast("04:00:00+0300"), isTZ(14400000000L, 10800));
-        assertThat(TimeTZType.INSTANCE.implicitCast("04:00:00+03:00"), isTZ(14400000000L, 10800));
-        assertThat(TimeTZType.INSTANCE.implicitCast("04:00:00.123456789+03:00"), isTZ(14400123456L, 10800));
-        assertThat(TimeTZType.INSTANCE.implicitCast("04:00:00+0000"), isTZ(14400000000L));
-        assertThat(TimeTZType.INSTANCE.implicitCast("04:00:00.123456789-0000"), isTZ(14400123456L));
+        assertThat(TimeTZType.INSTANCE.implicitCast("01:00:00     UTC", SESSION_SETTINGS), isTZ(3600000000L));
```
Comment (matriv) [inline server/src/test/java/io/crate/types/TimeTZTypeTest.java:70]: What do you think about defining an `implicitCast` method on each of those TypeTests, to avoid repeating the argument `SESSION_SETTINGS`?

File: server/src/test/java/io/crate/expression/scalar/ArraySumFunctionTest.java [hunk 3]
```diff
@@ -1,23 +1,28 @@
...
+import io.crate.metadata.CoordinatorTxnCtx;
+import io.crate.metadata.settings.SessionSettings;
+import io.crate.testing.TestingHelpers;
+import io.crate.types.ArrayType;
+import io.crate.types.DataType;
+import io.crate.types.DataTypes;
 
 public class ArraySumFunctionTest extends ScalarTestCase {
 
+    private final SessionSettings sessionSettings = CoordinatorTxnCtx.systemTransactionContext().sessionSettings();
```
Comment (matriv) [inline server/src/test/java/io/crate/expression/scalar/ArraySumFunctionTest.java:24]: Why here is not `static`?

File: server/src/main/java/io/crate/analyze/PartitionPropertiesAnalyzer.java [hunk 4]
```diff
@@ -57,7 +58,7 @@ public static PartitionName toPartitionName(RelationName relationName, List<Assi
 
         int idx = 0;
         for (Object o : properties.values()) {
-            values[idx++] = DataTypes.STRING.implicitCast(o);
+            values[idx++] = DataTypes.STRING.implicitCast(o, CoordinatorTxnCtx.systemTransactionContext().sessionSettings());
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/analyze/PartitionPropertiesAnalyzer.java:61]: Maybe move this outside of the loop to avoid creating a new context for each value.

File: server/src/main/java/io/crate/common/collections/MapComparator.java [hunk 5]
```diff
@@ -64,7 +65,7 @@ public static <K, V> int compareMaps(Map<K, V> m1, Map<K, V> m2) {
                     DataType leftType = DataTypes.guessType(thisValue);
                     int cmp = leftType.compare(
                         thisValue,
-                        leftType.implicitCast(otherValue)
+                        leftType.implicitCast(otherValue, CoordinatorTxnCtx.systemTransactionContext().sessionSettings())
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/common/collections/MapComparator.java:68]: Maybe move outside of the entrySet loop or create lazy only once if needed

**Review by mfussenegger — COMMENTED** [review]
I'm still not sure if adding the session settings to `implicitCast` is really the way to go. 

Some of the use-sites where we now use the system context look like they really shouldn't need it.

Fine for me to make the change, but if you've doubts as well maybe it would be better to limit it to explicitCast?

There are also a couple of TODOs left, do you intend to follow up on those later?

**Comment by seut** [comment]
@mfussenegger @matriv I've pushed another commit which reverts adding the `SessionSettings` to `implicitCast`, this also removes all outstanding TODOs. pls check.

File: server/src/test/java/io/crate/types/RegclassTypeTest.java [hunk 6]
```diff
@@ -6,7 +6,7 @@
  * you may not use this file except in compliance with the License.  You may
  * obtain a copy of the License at
  *
- *   http://www.apache.org/licenses/LICENSE-2.0
+ *     http://www.apache.org/licenses/LICENSE-2.0
```
Comment (matriv) [inline server/src/test/java/io/crate/types/RegclassTypeTest.java:9]: Is this correct?

File: server/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java [hunk 7]
```diff
@@ -131,6 +131,21 @@ public static void register(ScalarFunctionModule module) {
         );
     }
 
+    public static String trim(String target, char charToTrim) {
```
Comment (matriv) [inline server/src/main/java/io/crate/expression/scalar/string/TrimFunctions.java:134]: How about moving it to `StringUtils` ?

File: server/src/test/java/io/crate/integrationtests/PgCatalogITest.java [hunk 8]
```diff
@@ -328,4 +328,15 @@ public void test_pg_constrains_conkey_array_populated() throws Exception {
         ));
 
     }
+
+    @UseRandomizedSchema(random = false)
+    @Test
+    public void test_pg_class_oid_equals_cast_of_string_to_regclass() {
+        execute("CREATE TABLE persons (x INT)");
+        execute("SELECT " +
```
Comment (matriv) [inline server/src/test/java/io/crate/integrationtests/PgCatalogITest.java:336]: This is not relevant to this PR:
Postgres behaves differently:
```
postgres=# SELECT '"marios"'::regclass oid_from_relname, oid FROM pg_class WHERE relname ='marios';
 oid_from_relname |  oid  
------------------+-------
 marios           | 24616
(1 row)

postgres=# SELECT '"marios"'::regclass::int oid_from_relname, oid FROM pg_class WHERE relname ='marios';
 oid_from_relname |  oid  
------------------+-------
            24616 | 24616
(1 row)
```

So, it doesn't do an implicit cast to int, should we follow this behaviour as well?

File: server/src/main/java/io/crate/types/Regclass.java [hunk 9]
```diff
@@ -57,9 +59,11 @@ public static Regclass primaryOid(RelationInfo relation) {
         );
     }
 
-    public static Regclass fromRelationName(String name) {
+    public static Regclass fromRelationName(String name, String currentSchema) {
+        name = trim(name, '"');
```
Comment (matriv) [inline server/src/main/java/io/crate/types/Regclass.java:63]: Again not 100% related to the PR:
Postgres:
```
postgres=# select '""marios'""::regclass;
ERROR:  zero-length delimited identifier at or near """"
LINE 1: select '""marios'""::regclass;
```
Crate:
```
cr> select '""marios""'::regclass;                                                                                                                       
+-------------+
| -1459601621 |
+-------------+
| -1459601621 |
+-------------+
SELECT 1 row in set (0.001 sec)
```

**Review by matriv — COMMENTED** [review]
Looks good! Left a few minor comments and a couple of questions.

File: server/src/main/java/io/crate/types/Regclass.java (hunk 9 above)
Comment (seut) [reply server/src/main/java/io/crate/types/Regclass.java:63]: Probably a type and you meant:
```
postgres=# select '""marios""'::regclass;
ERROR:  invalid name syntax
LINE 1: select '""marios""'::regclass;
```
I guess PG is parsing the string literal as a `name` type if casted to `regclass`. 
PG also allows to use such identifiers as a table name:
```
postgres=# create table """t2""" (id int);
CREATE TABLE
postgres=# \dt
              List of relations
 Schema |      Name       | Type  |  Owner   
--------+-----------------+-------+----------
 public | "t2"            | table | postgres
(1 row)
postgres=# select '"""t2"""'::regclass;
 regclass 
----------
 """t2"""
(1 row)
```

CrateDB doesn't allow it:
```
cr> create table """t2""" (id int);                                                                                                                                                                                                                 
InvalidRelationName[Relation name ""t2"" is invalid.]
```

So I think it's fine that we simply trim double quotes. We could also use a parser to ensure that the string literal contains a valid identifier, but I doubt a bit that this is worth doing.

File: server/src/test/java/io/crate/integrationtests/PgCatalogITest.java (hunk 8 above)
Comment (seut) [reply server/src/test/java/io/crate/integrationtests/PgCatalogITest.java:335]: At the moment we use the `regclass` type for oid's inside `pg_catalog` tables because we lack a dedicated `OID` type. That's why we default to return the `oid` of a regclass type at HTTP instead of the relation name like PG does.
Such we could only fix that once we implement a dedicated `OID` data type.

File: server/src/main/java/io/crate/types/Regclass.java (hunk 9 above)
Comment (seut) [reply server/src/main/java/io/crate/types/Regclass.java]: I've pushed a commit to use the SQL parser on string to regclass casts.

**Comment by seut** [comment]
This will also fix #10735.

File: server/src/test/java/io/crate/integrationtests/PgCatalogITest.java [hunk 10]
```diff
@@ -328,4 +327,15 @@ public void test_pg_constrains_conkey_array_populated() throws Exception {
...
+            " '\"persons\"'::regclass::integer oid_from_relname, " +
```
Comment (matriv) [inline server/src/test/java/io/crate/integrationtests/PgCatalogITest.java:336]: maybe it's better to remove the `::integer` cast so that in the future, we can easily catch and adjust the test, but as you like.

**Review by matriv — APPROVED** [review]
Thanks @seut!

Left a minor comment, no need to be addressed.
I'd also suggest to add a line in the documentation that this cast, since it's 100% postgres functionality, unlike postgres it doesn't actually check for an existing table with that name. Also that a cast to `::regclass` returns an int, where in postgres it returns a string, although for both the return type is `regclass`. If you agree, it can be done in a another PR, as it's not related to this change.

**Comment by seut** [comment]
@matriv 

> Also that a cast to ::regclass returns an int, where in postgres it returns a string, although for both the return type is regclass. 

Yes I think we should followup with creating a dedicated `OID` type and use it inside pg_catalog tables where currently `REGCLASS` is (wrongly) used. Afterwards we can change `REGCLASS` to return a string by default.

**Comment by seut** [comment]
@matriv 
> I'd also suggest to add a line in the documentation that this cast, since it's 100% postgres functionality, unlike postgres it doesn't actually check for an existing table with that name.

I've added a note to the `regclass` documentation, see fixup commit.

**Review by matriv — APPROVED** [review]
LGTM. Thx a lot @seut!

**Review by mfussenegger — APPROVED** [review]

**Comment by seut** [comment]
retest this please

unrelated known LR test failure
