### PR TITLE
re-enables range query support on the `_id` + `_uid` columns

### LINKED ISSUE #5845: Range Queries on _id field
**CrateDB version**:
2.0.2

**JVM version**:
8

**OS version / environment description**:
OSX / Linux

**Problem description**:

In Crate 2.0.2 it's not possible anymore to do range queries on the `_id` field. This was possible in Crate version 1.1.6. 

The error message:
`SQLActionException[UnhandledServerException: java.lang.IllegalArgumentException: Field [_uid] of type [_uid] does not support range queries]`

A quick fix for the problem is to use a cast to string, but this will probably make the query slow on large tables:

`SELECT ts, _id FROM test WHERE CAST(_id AS STRING) > 'AVz32Sa6bDpzOF_VFngM' ORDER BY ts, _id LIMIT 1`

Use case is to batch process data based on a timestamp and be able to handle data with same timestamp exactly once.

**Steps to reproduce**:

CREATE TABLE test (ts TIMESTAMP);
INSERT INTO test (ts) VALUES ('2017-01-01'), ('2017-01-01'), ('2017-01-02');
SELECT ts, _id FROM test ORDER BY ts, _id LIMIT 1;
SELECT ts, _id FROM test WHERE _id > 'AVz32Sa6bDpzOF_VFngM' ORDER BY ts, _id LIMIT 1;

### PR DESCRIPTION
**Pull request by seut**
also see crate/elasticsearch#123
fixes #5845

also throw exception when using the `_raw` column inside a where clause instead of silently ignoring it.

### CODE REVIEW

File: sql/src/test/java/io/crate/integrationtests/WhereSystemColumnIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+        refresh();
+        execute("select _uid from t1 order by _uid limit 1");
+        String _uid = (String) response.rows()[0][0];
+
+        execute("select * from t1 where _uid > ?", new Object[]{_uid});
+        assertThat(response.rowCount(), is(2L));
+    }
+
+    @Test
+    public void testRangeQueryOnDocThrowsException() throws Exception {
```
Comment (mfussenegger) [inline sql/src/test/java/io/crate/integrationtests/WhereSystemColumnIntegrationTest.java]: Would it make sense to do this as unit test instead in the LuceneQueryBuilderTest class? Maybe also the others, so that the tests aren't that expensive?

File: CHANGES.txt [hunk 2]
```diff
@@ -56,6 +56,13 @@ Changes
 Fixes
 =====
 
+ - Throw proper exception when using the ``_raw`` inside the where clause
```
Comment (mfussenegger) [inline CHANGES.txt]: I think `the` could be removed, or otherwise it should be extended to `using the _raw column`

Comment (seut) [inline CHANGES.txt]: yeah forgot the `column` ;)
