### PR TITLE
Fix exception thrown when aliased literals used in order by clause

### LINKED ISSUE #11372: ORDER BY on an integer constant fails if using an alias
**CrateDB version**:
4.5.1

**Environment description**:
Docker v20.10.6, reproducible without Docker as well

**Problem description**:
Using an `ORDER BY` clause on an integer constant with an alias throws an exception, which incorrectly claims that a non-integer constant has been used.

**Steps to reproduce**:
```sql
create table test (a integer);

select 12 from test order by 1 limit 100;
-- pass: empty result set returned

select 12 as b from test order by 1 limit 100;
-- fail: UnsupportedFeatureException[Using a non-integer constant in ORDER BY is not supported]
```

<details>
  <summary>Full stacktrace</summary>

```
io.crate.exceptions.UnsupportedFeatureException: Using a non-integer constant in ORDER BY is not supported
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:139)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:126)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:162)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:118)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2321)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:116)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:79)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:166)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:136)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:85)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.UnsupportedOperationException: Using a non-integer constant in ORDER BY is not supported
	at io.crate.execution.engine.sort.SortSymbolVisitor.visitSymbol(SortSymbolVisitor.java:240)
	at io.crate.execution.engine.sort.SortSymbolVisitor.visitSymbol(SortSymbolVisitor.java:68)
	at io.crate.expression.symbol.SymbolVisitor.visitLiteral(SymbolVisitor.java:54)
	at io.crate.expression.symbol.Literal.accept(Literal.java:147)
	at io.crate.execution.engine.sort.SortSymbolVisitor.visitAlias(SortSymbolVisitor.java:234)
	at io.crate.execution.engine.sort.SortSymbolVisitor.visitAlias(SortSymbolVisitor.java:68)
	at io.crate.expression.symbol.AliasSymbol.accept(AliasSymbol.java:68)
	at io.crate.execution.engine.sort.SortSymbolVisitor.generateSortFields(SortSymbolVisitor.java:108)
	at io.crate.execution.engine.sort.LuceneSortGenerator.generateLuceneSort(LuceneSortGenerator.java:47)
	at io.crate.execution.engine.collect.LuceneShardCollectorProvider.getOrderedCollector(LuceneShardCollectorProvider.java:245)
	at io.crate.execution.engine.collect.ShardCollectorProvider.lambda$getFutureOrderedCollector$3(ShardCollectorProvider.java:171)
	at org.elasticsearch.index.shard.IndexShard.awaitShardSearchActive(IndexShard.java:3164)
	at io.crate.execution.engine.collect.ShardCollectorProvider.getFutureOrderedCollector(ShardCollectorProvider.java:169)
	at io.crate.execution.engine.collect.sources.ShardCollectSource.createMultiShardScoreDocCollector(ShardCollectSource.java:359)
	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterator(ShardCollectSource.java:294)
	at io.crate.execution.engine.collect.MapSideDataCollectOperation.createIterator(MapSideDataCollectOperation.java:58)
	at io.crate.execution.engine.collect.CollectTask.start(CollectTask.java:162)
	at io.crate.execution.jobs.RootTask.start(RootTask.java:191)
	at io.crate.execution.engine.JobLauncher.setupTasks(JobLauncher.java:241)
	at io.crate.execution.engine.JobLauncher.execute(JobLauncher.java:154)
	at io.crate.planner.operators.LogicalPlanner.executeNodeOpTree(LogicalPlanner.java:531)
	at io.crate.planner.operators.LogicalPlanner.doExecute(LogicalPlanner.java:482)
	at io.crate.planner.operators.LogicalPlanner.execute(LogicalPlanner.java:455)
	at io.crate.planner.operators.LogicalPlan.executeOrFail(LogicalPlan.java:220)
	at io.crate.planner.Plan.execute(Plan.java:74)
	at io.crate.action.sql.Session.singleExec(Session.java:658)
	at io.crate.action.sql.Session.execute(Session.java:466)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:266)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:206)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:115)
	... 43 more
```
</details>

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB

Fixed an issue that threw an exception when ``ORDER BY`` clauses contain aliased literals. closes #11372

```SQL
before:
select 12 as b from test order by 1 limit 100;
-- fail: UnsupportedFeatureException[Using a non-integer constant in ORDER BY is not supported]

after:
DROP OK, 1 row affected  (0.179 sec)
cr> create table t (int int);                                                                                                                                 
CREATE OK, 1 row affected  (0.387 sec)
cr> select 1 as a, 2 as b, 3 as c from t order by 3,2,1;                                                                                                      
+---+---+---+
| a | b | c |
+---+---+---+
+---+---+---+
SELECT 0 rows in set (0.088 sec)
```

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

File: server/src/main/java/io/crate/planner/operators/Collect.java [hunk 1]
```diff
@@ -155,7 +156,8 @@ public ExecutionPlan build(PlannerContext plannerContext,
                 order.map(binder)
                     // Filter out literal constants as ordering by constants is a NO-OP and also not supported
                     // on the collect operation.
-                    .exclude(s -> s instanceof Literal));
+                    .exclude(s -> s instanceof Literal ||
+                                  s instanceof AliasSymbol && ((AliasSymbol)s).symbol() instanceof Literal));
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/planner/operators/Collect.java:160]: Could use the new instanceof pattern match syntax:

```suggestion
                                  s instanceof AliasSymbol alias && alias.symbol() instanceof Literal));
```

**Review by mfussenegger — APPROVED** [review]

File: docs/appendices/release-notes/unreleased.rst [hunk 2]
```diff
@@ -113,3 +113,6 @@ Fixes
   ``CREATE TABLE`` statements to be rejected because the validation always used
   a fixed value of ``5`` instead of the actual number of shards declared within
   the ``CREATE TABLE`` statement.
+
+- Fixed an issue that threw an exception when ``ORDER BY`` clauses contain
+  aliased literals.
```
Comment (seut) [inline docs/appendices/release-notes/unreleased.rst:118]:
```suggestion
  the output column value of an aliased column.
```

File: server/src/test/java/io/crate/integrationtests/SelectOrderByIntegrationTest.java [hunk 3]
```diff
@@ -186,4 +186,16 @@ public void testOrderByLiteralConstant() {
...
+    @Test
+    public void testOrderByAliasedLiteral() {
+        execute("create table t1 (id int)");
+        execute("insert into t1 (id) values (1), (2)");
+        refresh();
+        execute("select 'a' as n1, 12 as n2, id as n3 from t1 order by 2, 3, 1");
+        assertThat(printedTable(response.rows()), Matchers.is("""
+                                                                  a| 12| 1
+                                                                  a| 12| 2
+                                                                  """));
```
Comment (seut) [inline server/src/test/java/io/crate/integrationtests/SelectOrderByIntegrationTest.java:199]: Can we convert this into a `CollectTest` unit test?
See e.g. https://github.com/crate/crate/blob/master/server/src/test/java/io/crate/planner/operators/JoinTest.java#L417 on how to build and test an execution plan.

**Review by seut — COMMENTED** [review]
Good catch, added some suggestions.

File: docs/appendices/release-notes/unreleased.rst (hunk 2 above)
Comment (seut) [reply docs/appendices/release-notes/unreleased.rst:118]: Please check if this suggestion may explain the case in a better way.

File: server/src/main/java/io/crate/planner/operators/Collect.java (hunk 1 above)
Comment (jeeminso) [reply server/src/main/java/io/crate/planner/operators/Collect.java:160]: Thank you, I will copy that in.

File: docs/appendices/release-notes/unreleased.rst (hunk 2 above)
Comment (jeeminso) [reply docs/appendices/release-notes/unreleased.rst:118]: Thanks, I made one more change on top of your suggestion, `the output column position or the alias name of an aliased column`
because it also fixes 
```sql
select 123 as alias from t order by alias
```

File: server/src/test/java/io/crate/integrationtests/SelectOrderByIntegrationTest.java (hunk 3 above)
Comment (jeeminso) [reply server/src/test/java/io/crate/integrationtests/SelectOrderByIntegrationTest.java:199]: I am looking into it now, Thanks!

Comment (jeeminso) [reply server/src/test/java/io/crate/integrationtests/SelectOrderByIntegrationTest.java]: Hi Basti, checked in the change, please check once again.

**Review by seut — APPROVED** [review]
👍
