### PR TITLE
optimize WHERE ref=ref

### LINKED ISSUE #7058: Queries against table with table.field_name != table.field_name failing
**CrateDB version**: 2.1.5

**JVM version**: OpenJDK 1.8.0_151

**OS version / environment description**: Ubuntu / AWS / Local SSD Raid-0

**Problem description**:
On the (admittedly silly) query including the condition `posts.domain_id != posts.domain_id` I am seeing a significant number of timeout errors.

ex:
```
(crate.client.exceptions.ConnectionError) No more Servers available, exception from last server:
HTTPConnectionPool(host='api02.voicegraph.org', port=4200):
 Read timed out. (read timeout=30) [SQL: 'SELECT posts.id AS posts_id, posts.by_line AS posts_by_line
    FROM posts
 WHERE posts.domain_id != posts.domain_id
       AND posts.by_line IS NOT NULL 
       AND posts.created_at > ?'] [parameters: ('2018-02-19T00:01:19.000000Z',)]
```

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
optmize `where ref = ref` to `true` or `ref is not null` depending on ref is 3vl.

closes #7058 

**benchmarks:**
note that I did `select 1` since `select *` would make V2 slower than V1 for some reason. It seems like reading/parsing storage can be safely ruled out.

optimized to `true`:
```
# Results (server side duration in ms)
V1: 4.6.0-e22bc135a8f915bb3b081ea773eaac96dc018b56
V2: 4.6.0-75150277d2ab96433efc6d889d0e62d57bc0dd46

Q: select 1 from tbl where device = device
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        2.754 ±    5.905 |      1.597 |      2.046 |      2.331 |    123.282 |
|   V2    |        2.110 ±    4.665 |      1.196 |      1.687 |      1.902 |    103.556 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -  26.47%                           -  19.24%   
There is a 94.39% probability that the observed difference is not random, and the best estimate of that difference is 26.47%
The test has no statistical significance


System/JVM Metrics (durations in ms, byte-values in MB)
    |    YOUNG GC            |       OLD GC           |      HEAP         |     ALLOC     
    |  cnt      avg      max |  cnt      avg      max |  initial     used |     rate      total
 V1 |    1     7.99     7.99 |    0     0.00     0.00 |      268       46 |     0.00          0
 V2 |    1     3.33     3.33 |    0     0.00     0.00 |      268       41 |     0.00          0
    
V1 top allocation frames
  Integer.valueOf(int):9
  EstimateRowSize.applyAsLong(Row):7
  HashMap.getNode(Object):7
  UTF8JsonGenerator.writeStartArray():5
  ImmutableCollections$MapN.probe(Object):3
V2 top allocation frames
  ImmutableCollections$MapN.probe(Object):6
  RetryOnFailureResultReceiver.setNextRow(Row):5
  InputRow.get(int):5
  EstimateRowSize.applyAsLong(Row):5
  UTF8JsonGenerator._flushBuffer():4
```

optimized to `is not null`
```
# Results (server side duration in ms)
V1: 4.6.0-e22bc135a8f915bb3b081ea773eaac96dc018b56
V2: 4.6.0-75150277d2ab96433efc6d889d0e62d57bc0dd46

Q: select 1 from tbl where device = device
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        2.799 ±    5.093 |      1.581 |      2.095 |      2.350 |    105.051 |
|   V2    |        2.440 ±    4.023 |      1.420 |      1.890 |      2.132 |     87.256 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -  13.70%                           -  10.32%   
There is a 78.36% probability that the observed difference is not random, and the best estimate of that difference is 13.70%
The test has no statistical significance


System/JVM Metrics (durations in ms, byte-values in MB)
    |    YOUNG GC            |       OLD GC           |      HEAP         |     ALLOC     
    |  cnt      avg      max |  cnt      avg      max |  initial     used |     rate      total
 V1 |    1     7.35     7.35 |    0     0.00     0.00 |      268       44 |     0.00          0
 V2 |    1     7.79     7.79 |    0     0.00     0.00 |      268       45 |     0.00          0
    
V1 top allocation frames
  Integer.valueOf(int):9
  NumberOutput.outputInt(...):7
  TwoPhaseIterator$TwoPhaseIteratorAsDocIdSetIterator.doNext(int):5
  DirectByteBuffer.ix(int):5
  HashMap.getNode(Object):4
V2 top allocation frames
  InputRow.get(int):12
  JsonGeneratorImpl._verifyPrettyValueWrite(...):5
  RetryOnFailureResultReceiver.setNextRow(Row):4
  SingletonSortedNumericDocValues.nextDoc():4
  XContentBuilder.unknownValue(...):3
```

**benchmark details:**
```
cat specs/mysample.toml 
[setup]
statements = [
  "create table tbl (device int not null, payload object as (col int not null)) clustered into 1 shards"
]

  [[setup.data_files]]
  target = "tbl"
  source = "data/mysample.json"

[[queries]]
statement = "select 1 from tbl where device = device"
iterations = 500

[teardown]
statements = [
  "drop table tbl"
]
wc -l specs/data/mysample.json 
13600 specs/data/mysample.json
```
## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
Hello @mfussenegger, please have a look, this should fix #7058.
- this will rewrite ref!=ref, not(eq(ref,ref)), to not(true) then `EvaluatingNormalizer` should rewrite not(true) to false.
- could expand this to handle ref +1 = 1 + ref by implementing something like `Function.equivalent` but not sure if it is within the scope and how complex function reduction or equivalence check it should be able to handle.

File: server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java [hunk 1]
```diff
@@ -132,14 +135,22 @@ public Symbol tryApplyRules(Symbol node) {
     }
 
     private class Visitor extends FunctionCopyVisitor<Void> {
+        private Stack<io.crate.expression.symbol.Function> visitedFunctions = new Stack<>();
```
Comment (jeeminso) [inline server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java:138]: could be replace by a counter since the only usage right now is to check if the current node is the root or not.

File: server/src/test/java/io/crate/planner/optimizer/symbol/rule/SimplifyEqualsOperationOnIdenticalReferencesTest.java [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+            List.of(
+                NULLABLE_REF,
+                NULLABLE_REF
+            ),
+            DataTypes.BOOLEAN);
+        Match<Function> match = RULE.pattern().accept(functionToOptimize, Captures.empty());
+        Symbol optimizedFunction = null;
+        if (match.isPresent()) {
+            optimizedFunction = RULE.apply(match.value(), match.captures(), NODE_CONTEXT, null);
+        }
```
Comment (mfussenegger) [inline server/src/test/java/io/crate/planner/optimizer/symbol/rule/SimplifyEqualsOperationOnIdenticalReferencesTest.java:107]: Maybe worth asserting that the match is present?

File: server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java (hunk 1 above)
Comment (mfussenegger) [reply server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java:138]: Would at least change it to `ArrayDeque` to avoid the synchronization overhead that `Stack` has.

File: server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java [hunk 3]
```diff
@@ -132,14 +135,22 @@ public Symbol tryApplyRules(Symbol node) {
...
 
         @Override
         public Symbol visitFunction(io.crate.expression.symbol.Function symbol, Void context) {
+            visitedFunctions.push(symbol);
             var maybeTransformedSymbol = tryApplyRules(symbol);
             if (symbol.equals(maybeTransformedSymbol) == false) {
                 return maybeTransformedSymbol;
             }
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/planner/optimizer/symbol/Optimizer.java:146]: If this exists here, `visitedFunctions.pop` is not called and the symbol will stay in the stack.

File: server/src/test/java/io/crate/planner/optimizer/symbol/rule/SimplifyEqualsOperationOnIdenticalReferencesTest.java [hunk 4]
```diff
@@ -66,8 +65,10 @@
             return null;
         }
     };
-    private static final SimplifyEqualsOperationOnIdenticalReferences RULE =
-        new SimplifyEqualsOperationOnIdenticalReferences(FUNCTION_SYMBOL_RESOLVER);
+    private static final Optimizer OPTIMIZER = new Optimizer(COORDINATOR_TXN_CTX,
```
Comment (jeeminso) [inline server/src/test/java/io/crate/planner/optimizer/symbol/rule/SimplifyEqualsOperationOnIdenticalReferencesTest.java:68]: need Optimizer instance to be able to apply the rule multiple times

File: server/src/test/java/io/crate/planner/optimizer/symbol/rule/SimplifyEqualsOperationOnIdenticalReferencesTest.java [hunk 5]
```diff
@@ -188,12 +170,62 @@ public void testSimplifyRefEqRefWhenParentIsIgnore3vlFunction() {
...
+        Function functionToOptimize = new Function(
+            Ignore3vlFunction.SIGNATURE,
+            List.of(not),
+            DataTypes.BOOLEAN);
+        Symbol optimizedFunction = OPTIMIZER.optimize(functionToOptimize);
+        assertThat(optimizedFunction.toString(), is("ignore3vl((NOT true))"));
+    }
+
+    @Test
+    public void testMultipleApplicationOfSimplifyRefEqRef() {
```
Comment (jeeminso) [inline server/src/test/java/io/crate/planner/optimizer/symbol/rule/SimplifyEqualsOperationOnIdenticalReferencesTest.java:200]: this implicitly tests `Optimizer.Visitor`. If the previously visited `Function` is not properly popped, `right` will be simplified to `true`.

**Review by mfussenegger — APPROVED** [review]

**Comment by jeeminso** [comment]
@mfussenegger Hello Jordi, could have a look at my measurements? If I do `select *` the gain is ~5% or sometimes slower than before. Please check my revised measurements still shows that this change is worth to be merged.

**Comment by mfussenegger** [comment]
@jeeminso yes still worth it. I suspect the difference will be more significant the more data you have.
