### PR TITLE
Include numeric parameters when binding function return types

### LINKED ISSUE #15279: Flaky wrong results when casting to numeric in SUM aggregation
### CrateDB version

5.2.2

### CrateDB setup information

2 nodes (<- might be necessary)

### Problem description

Flaky wrong results when casting to numeric in SUM aggregation

### Steps to Reproduce

Most likely needs a multi-node cluster to reproduce

```sql
DROP TABLE IF EXISTS t01;
CREATE TABLE IF NOT EXISTS t01 (txt TEXT, val DOUBLE PRECISION);
INSERT INTO t01 VALUES ('a', 1.0), ('a', null);
REFRESH TABLE t01;

SELECT
        txt,
        SUM(val) AS val,
        SUM(val::NUMERIC) AS val2
FROM t01
GROUP BY txt;
```

```
+----------------------------------------------------------------------------------+
| QUERY PLAN                                                                       |
+----------------------------------------------------------------------------------+
| Eval[txt, sum(val) AS val, sum(cast(val AS numeric)) AS val2] (rows=unknown)     |
|   └ GroupHashAggregate[txt | sum(val), sum(cast(val AS numeric))] (rows=unknown) |
|     └ Collect[doc.t01 | [val, cast(val AS numeric), txt] | true] (rows=unknown)  |
+----------------------------------------------------------------------------------+
```

### Actual Result

```md
+-----+-----+------+
| txt | val | val2 |
+-----+-----+------+
| a   | 1.0 |   10 |
+-----+-----+------+
```

or sometimes

```md
+-----+-----+------+
| txt | val | val2 |
+-----+-----+------+
| a   | 1.0 |  1.0 |
+-----+-----+------+
```

### Expected Result

```md
+-----+-----+------+
| txt | val | val2 |
+-----+-----+------+
| a   | 1.0 |  1.0 |
+-----+-----+------+
```

### PR DESCRIPTION
**Pull request by romseygeek**
Some data types are parametrized for precision or storage length, and 
this information needs to be preserved when binding function signatures. 
This is particularly important for numeric types, where the precision 
parameter changes how values sent across the wire are interpreted by 
the receiver.

This changes SignatureBinder to include numeric parameters from input 
types when binding its return type. If there are multiple input arguments 
with different parameters, type compatibility is used to select the best 
type to use.

Fixes #15279

### CODE REVIEW

File: server/src/main/java/io/crate/metadata/functions/BoundSignature.java [hunk 1]
```diff
@@ -25,10 +25,7 @@
 
 import io.crate.types.DataType;
 
-public final class BoundSignature {
-
-    private final List<DataType<?>> argTypes;
-    private final DataType<?> returnType;
+public record BoundSignature(List<DataType<?>> argTypes, DataType<?> returnType) {
```
Comment (romseygeek) [inline server/src/main/java/io/crate/metadata/functions/BoundSignature.java:29]: Note for reviewers: I needed an equals and a toString to make testing easier, so converting this to a record seemed easiest

File: server/src/main/java/io/crate/metadata/functions/SignatureBinder.java [hunk 2]
```diff
@@ -345,7 +356,7 @@ private BoundVariables iterativeSolve(List<TypeConstraintSolver> constraints) {
     }
 
     private boolean allTypeVariablesBound(BoundVariables boundVariables) {
-        return boundVariables.getTypeVariableNames().equals(typeVariableConstraints.keySet());
```
Comment (romseygeek) [inline server/src/main/java/io/crate/metadata/functions/SignatureBinder.java:348]: This change is due to the fact that the bindings may now include parametrized types (eg `numeric=>numeric(10)`) that are not included as type variables in the signature declaration.

File: server/src/main/java/io/crate/types/NumericType.java [hunk 3]
```diff
@@ -200,6 +200,11 @@ public TypeSignature getTypeSignature() {
         }
     }
 
+    @Override
+    public Integer characterMaximumLength() {
```
Comment (romseygeek) [inline server/src/main/java/io/crate/types/NumericType.java:204]: This feels like a bit of a hack to be honest, but it fixes things for now.  In a follow-up we should change the TypeCompatibility code to delegate things into the types themselves rather than having some special-case logic for types that implement this values.

File: server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java [hunk 4]
```diff
@@ -566,7 +566,7 @@ public void test_count_distinct_on_length_limited_varchar_preserves_varchar_type
             .build();
 
         Symbol symbol = executor.asSymbol("count(distinct name)");
-        assertThat(symbol).isFunction("collection_count", List.of(new ArrayType<>(DataTypes.STRING)));
+        assertThat(symbol).isFunction("collection_count", List.of(new ArrayType<>(StringType.of(10))));
```
Comment (romseygeek) [inline server/src/test/java/io/crate/analyze/SelectStatementAnalyzerTest.java:569]: The parameters of input types are now preserved during bindings.

File: server/src/main/java/io/crate/types/NumericType.java (hunk 3 above)
Comment (romseygeek) [reply server/src/main/java/io/crate/types/NumericType.java:204]: ++, I can do that.  I'll open a separate PR for it I think, as it's its own useful bit of work.

It does mean that `TypeCompatibility#typeCompatibilityForParametrizedType` will now have three different special cases in it, which indicates to me that we should be pushing these comparisons into the data types themselves.  But that can be done later, it's a bigger change and I don't want it to slow this bugfix down.

Comment (romseygeek) [reply server/src/main/java/io/crate/types/NumericType.java:204]: `numeric` types are never actually stored, they're only generated from calculations on other rows as eg aggregations.  So would they even show up in `information_schema.columns`?

Comment (mfussenegger) [reply server/src/main/java/io/crate/types/NumericType.java:204]: Good point - they wouldn't show up - but still feels a bit error prone to use the wrong property.
Is it much effort to add the new one?

Unrelated to this PR - I had been wondering if we lack some kind of type family concept. So functions could bind to "numbers" or "characterSequence" and they'd work for all kinds of numbers or for char/varchar/string

Comment (romseygeek) [reply server/src/main/java/io/crate/types/NumericType.java:204]: I think it's still worth adding the new property, it just makes it a bit tricky to test in isolation.

File: server/src/main/java/io/crate/metadata/functions/SignatureBinder.java (hunk 2 above)
Comment (matriv) [reply server/src/main/java/io/crate/metadata/functions/SignatureBinder.java:348]: Could you please add this as a comment in the code, I think it could be useful for someone looking into this in the future.

File: server/src/test/java/io/crate/types/TypeCompatibilityTest.java [hunk 5]
```diff
@@ -39,4 +39,5 @@ void test_get_common_type_for_text_with_len_limit_return_text_with_highest_lengt
         var commonType = TypeCompatibility.getCommonType(StringType.of(2), StringType.of(1));
         assertThat(commonType, is(StringType.of(2)));
     }
+
```
Comment (matriv) [inline server/src/test/java/io/crate/types/TypeCompatibilityTest.java:52]: apologies for the nitpick: since this file is not touched for the fix, it could be confusing when git checking the history (high level).

File: server/src/main/java/io/crate/types/TypeSignature.java [hunk 6]
```diff
@@ -201,7 +205,8 @@ public DataType<?> createType() {
                 if (!parameter.type().equals(TypeSignatureType.INTEGER_LITERAL_SIGNATURE)) {
                     throw new IllegalArgumentException(
                         "The signature type of the based data type parameters can only be: "
-                        + TypeSignatureType.INTEGER_LITERAL_SIGNATURE.toString());
+                        + TypeSignatureType.INTEGER_LITERAL_SIGNATURE
+                    + " but was " + parameter.type());
```
Comment (matriv) [inline server/src/main/java/io/crate/types/TypeSignature.java:209]: nit: indentation seems different than previous lines.

File: server/src/main/java/io/crate/types/TypeSignature.java [hunk 7]
```diff
@@ -233,6 +238,10 @@ public String toString() {
         return typeName.toString();
     }
 
+    public boolean equalsIgnoringParameters(TypeSignature o) {
```
Comment (matriv) [inline server/src/main/java/io/crate/types/TypeSignature.java:241]: only a suggestion to shorten the name (also fine as is):
```suggestion
    public boolean equalsIgnoreParams(TypeSignature o) {
```

File: server/src/test/java/io/crate/integrationtests/SumAggregationCastingIT.java [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+
+package io.crate.integrationtests;
+
+import static io.crate.testing.Asserts.assertThat;
+
+import org.elasticsearch.test.IntegTestCase;
+import org.junit.Test;
+
+@IntegTestCase.ClusterScope(numDataNodes = 2, supportsDedicatedMasters = false, numClientNodes = 0)
+public class SumAggregationCastingIT extends IntegTestCase {
```
Comment (matriv) [inline server/src/test/java/io/crate/integrationtests/SumAggregationCastingIT.java:30]: Since we have unit tests, maybe just add the test to the existing:
`AggregateExpressionIntegrationTest`?
(Although we don't force at least 2 nodes currently, maybe just add `minDataNodes` to the existing class, so we could catch such issues earlier?

File: server/src/test/java/io/crate/metadata/functions/SignatureBinderTest.java [hunk 9]
```diff
@@ -615,12 +642,31 @@ public void produces(BoundVariables expected) {
             assertThat(actual).isEqualTo(expected);
         }
 
+        public void hasReturnType(DataType<?> expected) {
+            BoundSignature actual = bind();
```
Comment (matriv) [inline server/src/test/java/io/crate/metadata/functions/SignatureBinderTest.java:646]: consider creating a custom assertj assertion (e.g. `SettingsAssert`) for BoundSignature, but given the method `bind()` which is needed, maybe doesn't make sense.

File: server/src/main/java/io/crate/types/TypeCompatibility.java [hunk 10]
```diff
@@ -91,6 +91,21 @@ private static DataType<?> typeCompatibilityForParametrizedType(DataType<?> from
         List<DataType<?>> fromTypeParameters = fromType.getTypeParameters();
         List<DataType<?>> toTypeParameters = toType.getTypeParameters();
 
+        // TODO this block is a bunch of special casing, can we push this into the
```
Comment (matriv) [inline server/src/main/java/io/crate/types/TypeCompatibility.java:94]: I agree, can be done as followup of course.

**Review by matriv — COMMENTED** [review]
Thx a lot @romseygeek!

Left some comments, mostly minor.
Additionally, please add a changelog entry for `5.6.1.rst` since this should be backported.

**Comment by BaurzhanSakhariev** [comment]
> Additionally, please add a changelog entry for `5.6.1.rst` since this should be backported.

5.6.2, 5.6.1 is already released

File: server/src/test/java/io/crate/integrationtests/SumAggregationCastingIT.java (hunk 8 above)
Comment (seut) [reply server/src/test/java/io/crate/integrationtests/SumAggregationCastingIT.java:30]: 👍  and I'd also only limit the setup by whats needed, so probably `minDataNodes` only.

**Review by matriv — APPROVED** [review]
Thank you! LGTM

**Comment by romseygeek** [comment]
@Mergifyio squash title+body
