### PR TITLE
handle NPE thrown from TransportSchemaUpdateAction.mergeIntoSource

### LINKED ISSUE #11722: NPE on INSERT into column in altered table
### CrateDB version

4.5.1

### CrateDB setup information

Number of nodes: 3
12 GB heap

### Steps to Reproduce

```
CREATE TABLE IF NOT EXISTS "doc"."0x001" (
   "ts" TIMESTAMP WITHOUT TIME ZONE,
   "stream_id" TEXT,
   "01_01" OBJECT,
   "01_02" OBJECT,
   "01_03" OBJECT,
....
"ts_partition" TIMESTAMP WITHOUT TIME ZONE GENERATED ALWAYS AS _cast(date_trunc('quarter', 'UTC', "ts"), 'timestamp without time zone')
)
CLUSTERED BY ("stream_id") INTO 6 SHARDS
PARTITIONED BY ("ts_partition")
WITH (
   "allocation.max_retries" = 5,
   "blocks.metadata" = false,
   "blocks.read" = false,
   "blocks.read_only" = false,
   "blocks.read_only_allow_delete" = false,
   "blocks.write" = false,
   codec = 'default',
   column_policy = 'strict',
   "mapping.total_fields.limit" = 1000,
   max_ngram_diff = 1,
   max_shingle_diff = 3,
   number_of_replicas = '0-1',
   "routing.allocation.enable" = 'all',
   "routing.allocation.total_shards_per_node" = -1,
   "store.type" = 'fs',
   "translog.durability" = 'REQUEST',
   "translog.flush_threshold_size" = 536870912,
   "translog.sync_interval" = 5000,
   "unassigned.node_left.delayed_timeout" = 60000,
   "write.wait_for_active_shards" = '1'
) 
```

Inserting works ok so far, then altered table:
`alter table "doc"."0x001" add column "02_0815" OBJECT;`

everything still works ok, but after a view days, we cannot insert into the new column 02_0815 anymore:
error: NullpointerException[null], code: 5000, trace: Java.Lang.NullpointerException
We insert via http and do not always get this error, but most of the time Status 200, and rowcount(s) : -2
Also tried inserting via the AdminUI, same result, NullpointerException[null] !
But: inserting into all the other columns still works !

Tried to create another OBJECT column in this table, same result.
At this point the table has: 

- 707 columns
- 132 MIO records
- Size 19.1 GB
- Shards 48

The sys.jobs_log table shows the insert statements, but error column is always null.

We then created another table with just 1 OBJECT column (and the other columns from the first table): inserting works as expected.

### Expected Result

INSERTING works or get a decent error message.

### Actual Result

error: NullpointerException[null], code: 5000, trace: Java.Lang.NullpointerException

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
closes #11722

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

File: server/src/main/java/io/crate/execution/ddl/TransportSchemaUpdateAction.java [hunk 1]
```diff
@@ -221,14 +222,14 @@ static void mergeIntoSource(Map<String, Object> source, Map<String, Object> mapp
             String key = updateEntry.getKey();
             Object updateValue = updateEntry.getValue();
             if (source.containsKey(key)) {
-                Object sourceValue = source.get(key);
+                Object sourceValue = Objects.requireNonNull(source.get(key), "schema metadata should not contain null-valued entries");
```
Comment (seut) [inline server/src/main/java/io/crate/execution/ddl/TransportSchemaUpdateAction.java:225]: Wouldn't this still result in an NPE if a source with existing NULL values (existing mapping inside a running older cluster) is processed?
I think we must handle NULL values here for this BWC reason.

Comment (jeeminso) [reply server/src/main/java/io/crate/execution/ddl/TransportSchemaUpdateAction.java]: Thank you for catching it. It would handle BWC by simply reverting the line you pointed, but I thought it would be more clear to handle it more explicitly.

**Review by seut — APPROVED** [review]
👍

**Comment by jeeminso** [comment]
retest this please

File: server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java [hunk 2]
```diff
@@ -236,31 +237,41 @@ private static String addExistingMeta(AlterTableRequest request, Map<String, Obj
         Map<String, Object> mappingDeltaAsMap = request.mappingDeltaAsMap();
         Map<String, Object> metaDelta = (Map<String, Object>) mappingDeltaAsMap.get("_meta");
         if (metaDelta != null) {
-            metaDelta.put("partitioned_by", currentMeta.getOrDefault("partitioned_by", List.of()));
-            metaDelta.putIfAbsent("primary_keys", currentMeta.get("primary_keys"));
+            if (currentMeta.get("partitioned_by") != null) {
+                metaDelta.put("partitioned_by", currentMeta.get("partitioned_by"));
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java:241]: It would be possible to avoid the duplicate `get` calls, e.g.:

```suggestion
    var partitionedBy = currentMeta.get("partitioned_by");
    if (partitionedBy != null) {
        metaDelta.put("partitioned_by", partitionedBy);
    }
```

Comment (jeeminso) [reply server/src/main/java/io/crate/metadata/cluster/AlterTableClusterStateExecutor.java:241]: ok Thanks, will make the changes
