### PR TITLE
Fix eval projection to support fewer outputs than its source

### LINKED ISSUE #17341: `IndexOutOfBoundsException` when using a view and ordering by a column that isn't selected
### CrateDB version

5.10.0 / 5.9.9

### CrateDB setup information

Standard node

### Problem description

There is an exception for the query given below.

### Steps to Reproduce

```sql
CREATE TABLE IF NOT EXISTS "doc"."t1" (
   "id" INTEGER NOT NULL,
   "propertyName" TEXT NOT NULL,
   "valueDatetime" TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS "doc"."t2" (
   "id" INTEGER NOT NULL,
   "propertyName" TEXT NOT NULL,
   "valueDatetime" TIMESTAMP WITHOUT TIME ZONE
);

INSERT INTO "doc"."t1" VALUES (1, 'test', NOW());
INSERT INTO "doc"."t2" VALUES (1, 'test', NOW());

CREATE OR REPLACE VIEW "doc"."v1" AS
SELECT "id", "propertyName", "valueDatetime"
FROM "doc"."t1"
UNION ALL
SELECT "id", "propertyName", "valueDatetime"
FROM "doc"."t2";

SELECT "id"
FROM "doc"."v1" v
ORDER BY v."valueDatetime"
LIMIT 100;
```

### Actual Result

```
io.crate.exceptions.SQLParseException: Couldn't create execution plan from logical plan because of: Index 1 out of bounds for length 1:
Rename[id] AS v (rows=unknown)
  └ Rename[id] AS doc.v1 (rows=unknown)
    └ Limit[100::bigint;0] (rows=unknown)
      └ Union[id] (rows=unknown)
        ├ OrderBy["valueDatetime" ASC] (rows=unknown)
        │  └ Collect[doc.t1 | [id, "valueDatetime"] | true] (rows=unknown)
        └ OrderBy["valueDatetime" ASC] (rows=unknown)
          └ Collect[doc.t2 | [id, "valueDatetime"] | true] (rows=unknown)
	at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:211)
	at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:200)
	at io.crate.rest.action.SqlHttpHandler.sendResponse(SqlHttpHandler.java:176)
	at io.crate.rest.action.SqlHttpHandler.lambda$channelRead0$0(SqlHttpHandler.java:130)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:931)
	at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2401)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:128)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:87)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.protocols.http.HttpBlobHandler.channelRead0(HttpBlobHandler.java:159)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.crate.auth.HttpAuthUpstreamHandler.handleHttpChunk(HttpAuthUpstreamHandler.java:158)
	at io.crate.auth.HttpAuthUpstreamHandler.channelRead0(HttpAuthUpstreamHandler.java:95)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at org.elasticsearch.transport.netty4.Netty4InboundStatsHandler.channelRead(Netty4InboundStatsHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1503)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1366)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1415)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:868)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.lang.IllegalArgumentException: Couldn't create execution plan from logical plan because of: Index 1 out of bounds for length 1:
Rename[id] AS v (rows=unknown)
  └ Rename[id] AS doc.v1 (rows=unknown)
    └ Limit[100::bigint;0] (rows=unknown)
      └ Union[id] (rows=unknown)
        ├ OrderBy["valueDatetime" ASC] (rows=unknown)
        │  └ Collect[doc.t1 | [id, "valueDatetime"] | true] (rows=unknown)
        └ OrderBy["valueDatetime" ASC] (rows=unknown)
          └ Collect[doc.t2 | [id, "valueDatetime"] | true] (rows=unknown)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.get(ArrayList.java:428)
	at io.crate.common.collections.Lists$LazyMapList.get(Lists.java:385)
	at io.crate.execution.dsl.projection.EvalProjection.castValues(EvalProjection.java:58)
	at io.crate.planner.operators.Union.addCastsForIncompatibleObjects(Union.java:171)
	at io.crate.planner.operators.Union.build(Union.java:100)
	at io.crate.planner.operators.Limit.build(Limit.java:111)
	at io.crate.planner.operators.Rename.build(Rename.java:193)
	at io.crate.planner.operators.Rename.build(Rename.java:193)
	at io.crate.planner.operators.RootRelationBoundary.build(RootRelationBoundary.java:60)
	at io.crate.planner.operators.LogicalPlanner.getNodeOperationTree(LogicalPlanner.java:620)
	at io.crate.planner.operators.LogicalPlanner.doExecute(LogicalPlanner.java:599)
	at io.crate.planner.operators.LogicalPlanner.execute(LogicalPlanner.java:569)
	at io.crate.planner.operators.LogicalPlan.executeOrFail(LogicalPlan.java:216)
	at io.crate.planner.Plan.execute(Plan.java:74)
	at io.crate.session.Session.singleExec(Session.java:832)
	at io.crate.session.Session.execute(Session.java:583)
	at io.crate.rest.action.SqlHttpHandler.executeSimpleRequest(SqlHttpHandler.java:273)
	at io.crate.rest.action.SqlHttpHandler.handleSQLRequest(SqlHttpHandler.java:220)
	at io.crate.rest.action.SqlHttpHandler.channelRead0(SqlHttpHandler.java:127)
	... 59 more
Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	... 82 more
```

### Expected Result

Successful execution.

### PR DESCRIPTION
**Pull request by seut**
The Eval projection has a logic to add casts to its source outputs to a given list of target types (its own outputs). This is e.g. needed for Union's to ensure that all source outputs are cast to the same type.
In some situations the source can contain more symbols than the given target types to cast to.

Closes #17341.

### CODE REVIEW

File: server/src/test/java/io/crate/planner/UnionPlannerTest.java [hunk 1]
```diff
@@ -279,4 +283,33 @@ public void test_union_works_when_both_sides_have_no_outputs_to_keep_on_prunning
         );
     }
 
+    /*
+     * https://github.com/crate/crate/issues/17341
+     */
+    @UseRandomizedOptimizerRules(alwaysKeep = {MoveOrderBeneathUnion.class, MoveOrderBeneathEval.class, RemoveRedundantEval.class})
```
Comment (mkleen) [inline server/src/test/java/io/crate/planner/UnionPlannerTest.java:289]: The annotation `@UseRandomizedOptimizerRules` is only applicable in Integration Tests. Here, it has no effect. So we can remove it.

**Review by mkleen — APPROVED** [review]
LGTM. I have only one minor request.

File: server/src/test/java/io/crate/planner/UnionPlannerTest.java (hunk 1 above)
Comment (seut) [reply server/src/test/java/io/crate/planner/UnionPlannerTest.java:289]: So when using `SQLExecutor` all optimizer rules are always used?

**Comment by seut** [comment]
re-test this please

unrelated flaky CAS failure

**Comment by seut** [comment]
@mergifyio requeue

**Comment by BaurzhanSakhariev** [comment]
We need 5.9.10 on master, I will add it
