### PR TITLE
Use Column store for MIN/MAX aggregations on NUMERIC

### LINKED ISSUE #17372: Use Column store for MIN/MAX aggregations on NUMERIC
With: https://github.com/crate/crate/pull/17371 support for MIN/MAX on numeric is added.
(Previously, the NUMERIC values where casted to string, leading to wrong results)

Add support for DocValuesAggregator for MIN/MAX on `NUMERIC` type.

### PR DESCRIPTION
**Pull request by hariso**
## Summary of the changes / Why this improves CrateDB

Fixes https://github.com/crate/crate/issues/17372.

I've also tested manually with the column store enabled/disabled (with the tables below).

As a future improvement, it's probably possible to unify the implementations for `min` and `max`. The difference is just in the comparators used in `reduce()` (just the opposite) and the starting values. 

Test tables:

```sql
CREATE TABLE my_table_no_columnstore (
    int_col INTEGER STORAGE WITH (columnstore = false),
    str_col TEXT STORAGE WITH (columnstore = false),
    compact_num_col NUMERIC(10, 3) STORAGE WITH (columnstore = false),
    large_num_col NUMERIC(20, 3) STORAGE WITH (columnstore = false)
);

CREATE TABLE my_table_default (
    int_col INTEGER,
    str_col TEXT,
    compact_num_col NUMERIC(10, 3),
    large_num_col NUMERIC(20, 3)
);
```

## Checklist

 - [x] Added an entry in the latest `docs/appendices/release-notes/<x.y.0>.rst` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes (not done, no user-facing changes)
 - [x] Touched code is covered by tests
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in the latest `docs/appendices/release-notes/<x.y.0>.rst`
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

File: server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java [hunk 1]
```diff
@@ -313,6 +314,24 @@ public Object reduce(RamAccounting ramAccounting, Object state1, Object state2)
...
+                                                           List<Reference> aggregationReferences,
+                                                           DocTableInfo table,
+                                                           Version shardCreatedVersion,
+                                                           List<Literal<?>> optionalParams) {
+            Reference reference = getAggReference(aggregationReferences);
+            if (reference == null) {
+                return null;
+            }
+            DataType<?> valueType = reference.valueType();
+            if (valueType instanceof NumericType) {
```
Comment (hariso) [inline server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java:330]: @mfussenegger In the original investigation of yours here: https://github.com/crate/crate/commit/abaa9a3495ba3943e9532f0dc6be1d586144fa9b, you also `precision != null`. I believe there was a special reason for it? 

I left it out here, because:
* `getNumericDocValueAggregator` throws an exception if the precision is not provided.
* `sum()` works the same way
* it's not possible to create a numeric column without a precision.

Might I be missing something?

File: docs/appendices/release-notes/6.4.0.rst [hunk 2]
```diff
@@ -85,7 +85,9 @@ Scalar and Aggregation Functions
 Performance and Resilience Improvements
 ---------------------------------------
 
-None
+
+- The :ref:`min() <aggregation-min>` and :ref:`max() <aggregation-max>` aggregations
+  for the :ref:`NUMERIC <data-types-numeric>` type now utilize the column store.
```
Comment (mfussenegger) [inline docs/appendices/release-notes/6.4.0.rst]:
```suggestion
- Improved the performance of the :ref:`min() <aggregation-min>` and
  :ref:`max() <aggregation-max>` aggregations for columns of type :ref:`NUMERIC
  <data-types-numeric>`.
```

Strictly speaking it already used the column store before - but with slower abstractions.

File: server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java (hunk 1 above)
Comment (mfussenegger) [reply server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java:330]: The contract for `getDocValueAggregator` is that it is entirely optional - if there is no optimized version for an aggregation it should return `null`, not fail.


But you're right in omitting the precision check here - instead we should update `getNumericDocValueAggregator` to return null if the precision is missing instead of failing.

File: server/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java [hunk 3]
```diff
@@ -58,13 +130,27 @@ public void test_function_implements_doc_values_aggregator_for_numeric_types() {
         for (var dataType : DataTypes.NUMERIC_PRIMITIVE_TYPES) {
             assertHasDocValueAggregator(MaximumAggregation.NAME, List.of(dataType));
         }
+        assertHasDocValueAggregator(MaximumAggregation.NAME, List.of(new NumericType(6, 2)));
+    }
+
+    @Test
+    public void test_numeric_aggregation_not_supported_without_scale_or_precision() {
```
Comment (mfussenegger) [inline server/src/test/java/io/crate/execution/engine/aggregation/impl/MaximumAggregationTest.java:136]: See comment further above, `getDocValueAggregator` isn't supposed to fail

File: server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java (hunk 1 above)
Comment (hariso) [reply server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java:330]: Makes sense that we don't fail if there's no optimized path. Out of curiosity, is there a way for a user to know which path was taken? Logs, or something along those lines?

W/r to precision missing: is that actually possible? Reading the note at the end of the section [here](https://cratedb.com/docs/crate/reference/en/latest/general/ddl/data-types.html#numeric-precision-scale) makes me think it's not possible to have a numeric column without a precision.

Comment (mfussenegger) [reply server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java:330]: > Out of curiosity, is there a way for a user to know which path was taken? Logs, or something along those lines?

I don't think there's any logging in place. It's implementation detail only visible via profiling.

> is that actually possible?

Currently not, but if we change that, we don't want `getDocValueAggregator` to trigger a failure.

Comment (hariso) [reply server/src/main/java/io/crate/execution/engine/aggregation/impl/MaximumAggregation.java:330]: Thanks for the clarifications! I've pushed the updates.

File: docs/appendices/release-notes/6.4.0.rst [hunk 4]
```diff
@@ -85,7 +85,10 @@ Scalar and Aggregation Functions
 Performance and Resilience Improvements
 ---------------------------------------
 
-None
+
+- Improved the performance of the :ref:`min() <aggregation-min>` and
+  :ref:`max() <aggregation-max>` aggregations for columns of type :ref:`NUMERIC
+  <data-types-numeric>`.
```
Comment (hariso) [inline docs/appendices/release-notes/6.4.0.rst:91]: Btw, if you're interested, I can try providing a number for the performance improvement (it would probably look nice in the release notes:) ). I might need a bit of time to figure out how you're doing benchmarking, so it's probably better that I do that outside of this PR (not to block it).

**Comment by mfussenegger** [comment]
ok to test

**Review by mfussenegger — APPROVED** [review]

File: docs/appendices/release-notes/6.4.0.rst (hunk 4 above)
Comment (mfussenegger) [reply docs/appendices/release-notes/6.4.0.rst:91]: To verify the impact of a change we typically use the `compare_run.py` script from https://github.com/crate/crate-benchmarks with a cr8 spec file relevant to the change.

E.g. something like:

```
./compare_run.py \
    --v1 latest-nightly \
    --v2 /path/to/crate/app/target/crate-6.4.0-2026-04-21-07-17-bf7b5ad.tar.gz \
    --forks 1 \
    --env CRATE_HEAP_SIZE=2g \
    --spec specs/aggregate.toml
```

For this particular change you could update the `uservisits` table definition to use numeric for the `adRevenue`.
With that I get something like:

```
Q: select max("adRevenue") from uservisits
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |       32.423 ±    9.861 |     29.063 |     30.269 |     31.784 |    219.517 |
|   V2    |       11.385 ±    8.146 |      9.344 |     10.099 |     11.159 |    182.172 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -  96.04%                           -  99.93%
There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 96.04%
The test has statistical significance
```

But adding those numbers to the release notes is always a bit questionable because the improvement is per row - so the more rows you use to test, the bigger the change.

Comment (hariso) [reply docs/appendices/release-notes/6.4.0.rst:91]: Thanks a lot for the detailed steps! :+1: I'll try it out.:)

Yeah, numbers are tricky, especially when you add the setup (the machines, # of nodes, shards, etc.). 

My thinking is: if users know what the order of the improvements (a few % vs tens %) in a constant setup is, they might see a similar (albeit not identical) improvement themselves.

It might help them make a decision on how soon they want to upgrade. Or it might convince others to start using CrateDB.:)  

> because the improvement is per row - so the more rows you use to test, the bigger the change.

Hmm, what exactly do you mean by this?
