### PR TITLE
fix for copy-from-fail-fast test failure

### LINKED ISSUE #11956: [flaky test] test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node
Disable temporarily, #11957

```
## FAILURE: Test test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node(io.crate.integrationtests.CopyIntegrationTest)
java.lang.AssertionError: ## node: node_s0
{befb5a76-9b25-44ec-9a1a-725f67b22cf4=Task{id=befb5a76-9b25-44ec-9a1a-725f67b22cf4, tasks=[CollectTask{id=0, sharedContexts=SharedShardContexts{allocatedShards=[]}, consumer=DistributingConsumer{jobId=befb5a76-9b25-44ec-9a1a-725f67b22cf4, targetPhaseId=1, inputId=0, bucketIdx=0, downstreams=[Downstream{T73WU0yCRLOWImILnk_JKw', needsMoreData=true}]}, searchContexts=[], batchIterator=java.util.concurrent.CompletableFuture@25b5115f[Completed normally], finished=false}], closed=true}}

	at __randomizedtesting.SeedInfo.seed([9D69C4EF2BA53718:BA08338F368051F5]:0)
	at io.crate.integrationtests.SQLIntegrationTestCase.assertNoTasksAreLeftOpen(SQLIntegrationTestCase.java:320)
	at jdk.internal.reflect.GeneratedMethodAccessor99.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:770)
	at io.crate.integrationtests.SQLIntegrationTestCase.assertNoTasksAreLeftOpen(SQLIntegrationTestCase.java:272)
	... 11 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more
	Suppressed: java.lang.AssertionError: 
Expected: is <0>
     but: was <1>
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
[2021-12-06T17:27:58,979][INFO ][i.c.i.CopyIntegrationTest] [[Time-limited test]] before test

[2021-12-06T17:27:58,979][INFO ][i.c.i.CopyIntegrationTest] [[Time-limited test]] [CopyIntegrationTest#test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node]: setting up test

[2021-12-06T17:27:58,982][INFO ][o.e.c.m.MetadataIndexTemplateService] [[cratedb[node_s0][masterService#updateTask][T#1]]] adding template [random_index_template] for index patterns [*]

[2021-12-06T17:27:58,994][INFO ][i.c.i.CopyIntegrationTest] [[Time-limited test]] [CopyIntegrationTest#test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node]: all set up test

[2021-12-06T17:27:58,997][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:27:58,998][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

[2021-12-06T17:27:59,004][INFO ][o.e.c.m.MetadataCreateIndexService] [[cratedb[node_s0][masterService#updateTask][T#1]]] [mdkznwkxkckv.tbl] creating index, cause [api], templates [random_index_template], shards [4]/[0], mappings [default]

[2021-12-06T17:27:59,004][INFO ][o.e.c.r.a.AllocationService] [[cratedb[node_s0][masterService#updateTask][T#1]]] updating number_of_replicas to [1] for indices [mdkznwkxkckv.tbl]

[2021-12-06T17:27:59,190][INFO ][o.e.c.r.a.AllocationService] [[cratedb[node_s0][masterService#updateTask][T#1]]] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[mdkznwkxkckv.tbl][1]]]).

[2021-12-06T17:27:59,204][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s1][netty-worker][T#3]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:27:59,205][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s1][netty-worker][T#3]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

[2021-12-06T17:27:59,260][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_sc2][netty-worker][T#3]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:27:59,261][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_sc2][netty-worker][T#3]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

Error: 2-06T17:28:14,743][ERROR][i.c.t.SQLTransportExecutor] [[Time-limited test]] Error executing stmt=copy tbl from ? with (shared=true, fail_fast=true, bulk_size=2) return summary args=[file:///tmp/junit3437157713325476380/junit2543163352629364392/*] error=org.postgresql.util.PSQLException: ERROR: Job killed. NODE: node_s0

[URI: file:///tmp/junit3437157713325476380/junit2543163352629364392/d1c6c323-9c63-4b38-8ef7-2ffede3b729d, ERRORS: {failed to parse field [a] of type [integer]={count=1, line_numbers=[2]}}]

[2021-12-06T17:28:15,311][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:28:15,312][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

[2021-12-06T17:28:15,332][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:28:15,334][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

[2021-12-06T17:28:17,810][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s1][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:28:17,811][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s1][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

Error: 2-06T17:28:17,842][ERROR][i.c.t.SQLTransportExecutor] [[Time-limited test]] Error executing stmt=copy tbl from ? with (shared=true, fail_fast=true, bulk_size=2) return summary args=[file:///tmp/junit3437157713325476380/junit11625390341564996199/*] error=org.postgresql.util.PSQLException: ERROR: Job killed. NODE: node_s1

[URI: file:///tmp/junit3437157713325476380/junit11625390341564996199/eb5dcb05-28ac-4706-bf92-ba6c99db4697, ERRORS: {failed to parse field [a] of type [integer]={count=1, line_numbers=[2]}}]

[2021-12-06T17:28:17,952][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_sc2][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:28:17,953][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_sc2][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

[2021-12-06T17:28:17,978][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:28:17,979][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

[2021-12-06T17:28:18,030][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: extra_float_digits

[2021-12-06T17:28:18,037][INFO ][i.c.p.s.SetSessionPlan   ] [[cratedb[node_s0][netty-worker][T#1]]] SET SESSION STATEMENT WILL BE IGNORED: application_name

[2021-12-06T17:28:28,208][INFO ][i.c.i.CopyIntegrationTest] [[Time-limited test]] [CopyIntegrationTest#test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node]: cleaning up after test

[2021-12-06T17:28:28,219][INFO ][o.e.c.m.MetadataDeleteIndexService] [[cratedb[node_s0][masterService#updateTask][T#1]]] [mdkznwkxkckv.tbl/j6JuQ3wOTHe2CP_di_IhDw] deleting index

[2021-12-06T17:28:28,260][INFO ][o.e.c.m.MetadataIndexTemplateService] [[cratedb[node_s0][masterService#updateTask][T#1]]] removing template [random_index_template]

[2021-12-06T17:28:38,273][INFO ][i.c.i.CopyIntegrationTest] [[Time-limited test]] [CopyIntegrationTest#test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node]: cleaned up after test

[2021-12-06T17:28:38,273][INFO ][i.c.i.CopyIntegrationTest] [[Time-limited test]] after test

REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=9D69C4EF2BA53718 -Dtests.class=io.crate.integrationtests.CopyIntegrationTest -Dtests.method="test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node" -Dtests.locale=en-UG -Dtests.timezone=Universal

		at org.junit.Assert.assertThat(Assert.java:964)
		at org.junit.Assert.assertThat(Assert.java:930)
		at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:758)
		... 12 more

CopyIntegrationTest > test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node FAILED
```

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB

closes #11956

The main problem was `test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failure_from_single_node` timing out on windows workflow.

The number of rows to copy is lowered and then added retry mechanism to confirm fail_fast had an effect.

## Checklist

 - [ ] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
from https://github.com/crate/crate/issues/11956#issue-1073385745

The cause seems to be:
> at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:277)
```
for (TasksService tasksService : internalCluster().getInstances(TasksService.class)) {
    try {
        //noinspection unchecked
        Map<UUID, RootTask> contexts = (Map<UUID, RootTask>) activeTasks.get(tasksService);
        assertThat(contexts.size(), is(0));
    } catch (IllegalAccessException e) {
        throw new RuntimeException(e);
```
I think `CollectTask` is still alive because :
```
Task{
	id=befb5a76-9b25-44ec-9a1a-725f67b22cf4,
	tasks=[
		CollectTask{
			id=0,
			sharedContexts=SharedShardContexts{allocatedShards=[]},
			consumer=DistributingConsumer{
				jobId=befb5a76-9b25-44ec-9a1a-725f67b22cf4,
				targetPhaseId=1,
				inputId=0,
				bucketIdx=0,
				downstreams=[Downstream{T73WU0yCRLOWImILnk_JKw', needsMoreData=true}]
			},
			searchContexts=[],
			batchIterator=java.util.concurrent.CompletableFuture@25b5115f[Completed normally],   // --> batchIterator is finished,
			finished=false	                                                                      // --> but the consumer is not finished yet.
		}
	],
	closed=true
}
```

**Comment by jeeminso** [comment]
Hello @mfussenegger, could you have a look at this one? I believe it is just a testcase issue

File: server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java [hunk 1]
```diff
@@ -981,8 +992,8 @@ public void test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failu
                 nodeIds.size());
             URI passingUri = generateURIToBeConsumedByProvidedReaderNumber(
                 target,
-                Arrays.asList("{\"a\":123456789},".repeat(10000).split(",")),
-                (readerNumber+1) % nodeIds.size(), // even with #nodes > 2, it does not matter who gets the passing uri.
+                Arrays.asList("{\"a\":123456789},".repeat(20000).split(",")),
```
Comment (mfussenegger) [inline server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:995]: Why the increase of rows?

File: server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java [hunk 2]
```diff
@@ -995,25 +1006,37 @@ public void test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failu
...
 
-            // if the count is not less than 10000L, it is unclear whether fail_fast had any effect.
             execute("select count(*) from tbl where a = '123456789'");
-            assertTrue((long) response.rows()[0][0] < 10000L);
+            count = (long) response.rows()[0][0];
+            // on slower machines, it should be sufficient to check for the copy stmt did throw the expected exception only
+            if (System.getProperty("os.name").startsWith("Windows") == false) {
+                // if the count is not less than 20000L, it is unclear whether fail_fast had any effect.
+                assertTrue((count - accumulatePassingUriCount) < 20000L);
+            }
```
Comment (mfussenegger) [inline server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:1037]: Shouldn't the fail-fast always have an effect, even if the machine is slow?

If the error occurs before the last processed line, it shouldn't continue processing other lines, no?

File: server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java (hunk 1 above)
Comment (jeeminso) [reply server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:995]: sometimes the copy stmt on a node finished before receiving the fail_fast signal.

File: server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java (hunk 2 above)
Comment (jeeminso) [reply server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:1037]: > Shouldn't the fail-fast always have an effect, even if the machine is slow?

Sometimes copying 20k lines finishes before receiving the error.

> If the error occurs before the last processed line, it shouldn't continue processing other lines, no?

what I have seen is that the node waiting for the error already reached throttling state as it tries to copy 20k rows. Once it falls into the throttling state, regardless of fail_fast set to true of false, the copy stmt will execute indefinitely.

Comment (mfussenegger) [reply server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:1037]: > Sometimes copying 20k lines finishes before receiving the error.

If one of the lines contains an error, shouldn't it stop at that point?

Comment (jeeminso) [reply server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:1037]: yes it should, but what I am trying to test here is the error from one node to trigger error in another node. The 20k rows are without errors.

File: server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java [hunk 3]
```diff
@@ -968,8 +977,10 @@ public void test_copy_from_with_fail_fast_property_can_kill_all_nodes_with_failu
             nodeIds.add((String) response.rows()[i][1]);
         }
 
-        for (int i = 0; i < nodeIds.size(); i++) {
+        long accumulateFailingUriCount = 0;
+        long accumulatePassingUriCount = 0;
 
+        for (int i = 0; i < nodeIds.size(); i++) {
```
Comment (seut) [inline server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:983]: I don't completely understand this test scenario.
Afaik we want to test that the failing record is once consumed on the handler node and once on a non-handler node.
So wouldn't this be much simple if we create the dataset upfront with a concrete node/readerid and then execute the `COPY FROM` twice, once on node which consumes the error row (thus failure happen on the handler node) and once on the node which won't concume and error prone rows (thus failure will happen on a non-handler node).
Wouldn't this also make the scenario much more deterministic and safe?
As far as I understood we must somehow ensure that all nodes will still be processing rows when the error is happening. Thus if the error happens on the first row, the error propagation must be faster than consuming x rows.
But I wonder that we must create more rows to make it succeed on slower machines, I'd expect the opposite.

Comment (jeeminso) [reply server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:1000]: Thank you @seut, when I first noticed that the `x` rows are entirely consumed before the error propagation, my instinct was to increase `x`. Today I spent more time experimenting with reduced `x`, and realized that  increasing/decreasing `x` affects the mean of multiple trials of copy stmt not the variance. Now, I am trying with low `x` and repeated with a certain number of `maxTry` like my other tests to ignore the occasions with high variance.

Also, I agree to
> Wouldn't this also make the scenario much more deterministic and safe?

But, how could I find out which node is the handler node?

Comment (seut) [reply server/src/test/java/io/crate/integrationtests/CopyIntegrationTest.java:1000]: > But, how could I find out which node is the handler node?

It's about how to ensure that the statement will be send to a concrete node as the node receiving the statement is the handler node.
See e.g. https://github.com/crate/crate/blob/master/server/src/test/java/io/crate/integrationtests/ReadOnlyNodeIntegrationTest.java how this can be ensured.

So we'd create a dataset which ensures that e.g. the node stored inside `internalCluster().getNodeNames()[0]` will process the failing row. Then we'll issue the statement once against this node (error happens on the "handler" node) and once against the other node (error happens not on the "handler" node).

**Comment by jeeminso** [comment]
removed the loop and made the test more deterministic also, lowered the num rows to copy as well as  `waitUntilNoTasksAreLeftOpen(1L, MINUTES)`.

**Comment by jeeminso** [comment]
sorry for the false alarm, I am trying to reduce as much as possible and now hitting timeouts again.

**Comment by jeeminso** [comment]
hello @mfussenegger, @seut. Please review my changes, it is ready for review now. Thank you

**Comment by jeeminso** [comment]
Hello @seut, could you review my last commit?

File: server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java [hunk 4]
```diff
@@ -0,0 +1,359 @@
...
+        // without return summary
+        execute("COPY t FROM ? WITH (fail_fast = true, shared = false) return summary", new Object[]{target.toUri().toString() + "*"});
+        refresh();
+        execute("select * from t");
+        assertThat(response.rowCount(), is(6L * cluster().numDataNodes() * 2));
+    }
+
+    @UseJdbc(0)
+    @Test
+    public void test_copy_from_fail_fast_messages_with_passing_and_failing_uris() throws IOException {
```
[the remark this answers is not in the document]
Comment (jeeminso) [reply server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java:282]: this is to verify UpsertResultCollectors are working properly with or without `return summary`.

[the remark this answers is not in the document]
Comment (jeeminso) [reply server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java]: those two scenarios lead me to come up with `newSummaryOnFailOrRowCountOnSuccessCollector` but it is no longer needed. I added a simpler test case just to test `return summary` with `fail_fast` that only contains summary for a successful uri. Please check my last commit. Thank you

File: server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java [hunk 5]
```diff
@@ -0,0 +1,276 @@
...
+        );
+
+        execute("SELECT COUNT(*) FROM doc.t");
+        assertThat((long) response.rows()[0][0], lessThan(50L));
+    }
+
+    @Test
+    public void test_copy_from_fail_fast_without_return_summary_without_write_errors() throws IOException {
+        // fail_fast relies on return-summary logic in order to generate meaningful exception messages if fails.
+        // If passes, from the collected upsertResults, only the successRowCounts is used.
```
Comment (seut) [inline server/src/test/java/io/crate/integrationtests/CopyFromFailFastITest.java:246]: This comment still sounds to me as the new `fail-fast` logic does not change any logic if everything succeeds. Such I don't think this test case covers anything new. But also ok to keep it.

**Review by seut — APPROVED** [review]

**Comment by jeeminso** [comment]
Thank you, just fixed up comments to try to make it more clear of the different paths.. and squashed.
