### PR TITLE
Fix function symbol formatting, quote if name contains spaces

### LINKED ISSUE #9311: SHOW CREATE TABLE SqlException with TIMESTAMP WITHOUT TIME ZONE
**CrateDB version**: 4.0.4

**Environment description**:

Crate DB on single node Docker (vs. 18.06.1-ce) running on Ubuntu 18.04 VM

**Problem description**:

SHOW CREATE TABLE returns the following error, when used on a  table, that has a TIMESTAMP WITHOUT TIME ZONE field:
`SQLActionException[SQLParseException: line 1:14: mismatched input 'without' expecting {<EOF>, '[', 'OR', 'AND', 'IN', 'NOT', 'BETWEEN', 'LIKE', 'IS', '=', NEQ, '<', '<=', '>', '>=', '~', '!~', '~*', '!~*', '+', '-', '*', '/', '%', '||', '::'}]`
The created table can be used normally, I can insert, query, update.

**Steps to reproduce**:
Create table like so:
`CREATE TABLE create_test2 (
    ts TIMESTAMP WITHOUT TIME ZONE,
    ts_hour TIMESTAMP WITHOUT TIME ZONE DEFAULT date_trunc('hour', CURRENT_TIMESTAMP),
    id STRING,
    vst INT,
    dif STRING,
    topic STRING,
    data_obj OBJECT
) PARTITIONED BY (ts_hour);`
then
`SHOW CREATE TABLE create_test2` 
gives the error.
If I create the table with TIME ZONE, the SHOW CREATE TABLE query works, but this is not what I want.

**edit**:
actually the line:
`ts_hour TIMESTAMP WITHOUT TIME ZONE DEFAULT date_trunc('hour', CURRENT_TIMESTAMP)`
is what seems to cause the error

### PR DESCRIPTION
**Pull request by seut**
Function names containing spaces must be quoted when printed.
Fixes #9311.

### CODE REVIEW

**Comment by kovrus** [comment]
I am wondering whether it is even ok to have function names with whitespaces? 🤔 Maybe we should just build the correct names here https://github.com/crate/crate/blob/master/sql/src/main/java/io/crate/expression/scalar/cast/CastFunctionResolver.java#L63

**Comment by seut** [comment]
@kovrus Function names are defined as identifiers by the parser and thus valid for quoting.

File: sql/src/main/java/io/crate/expression/symbol/format/FunctionFormatSpec.java [hunk 1]
```diff
@@ -50,7 +50,12 @@
     FunctionFormatSpec NAME_PARENTHESISED_ARGS = new FunctionFormatSpec() {
         @Override
         public String beforeArgs(Function function) {
-            return function.info().ident().name() + PAREN_OPEN;
+            String funcName = function.info().ident().name();
+            if (funcName.contains(" ")) {
```
Comment (kovrus) [inline sql/src/main/java/io/crate/expression/symbol/format/FunctionFormatSpec.java]: we can also use `Identifiers.quoteIfNeeded`
