### PR TITLE
Optimize fetch performance for sequential value retrieval

### LINKED ISSUE #10816: Performance regression for normal select with order by
image

I think around that time we updated Lucene.
We should investigate this before the 4.4 release.

Running the benchmark case from [crate-benchmarks](https://github.com/crate/crate-benchmarks) with git bisect as described [here](https://github.com/mfussenegger/cr8#find-regressions) may be a good option to find the commit that introduced the regression.

### PR DESCRIPTION
**Pull request by mkleen**
## Summary of the changes / Why this improves CrateDB

The fetch performance can be optimized for the case where the retrival is in sequential order by leveraging the merge instances of stored fields readers that are optimized for sequential access. 

```
Q: SELECT * FROM uservisits LIMIT 1000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |       43.509 ±    9.050 |     34.549 |     42.470 |     46.479 |    255.659 |
|   V2    |        9.481 ±    6.594 |      7.322 |      8.460 |      9.279 |    197.222 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               - 128.43%                           - 133.56%
There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 128.43%
The test has statistical significance

Q: select * from articles inner join colors on articles.id = colors.id order by articles.id limit 1000
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |       57.408 ±   34.947 |     47.715 |     51.859 |     54.174 |    525.007 |
|   V2    |       47.619 ±   28.969 |     39.616 |     42.811 |     45.897 |    440.282 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -  18.64%                           -  19.12%
There is a 99.76% probability that the observed difference is not random, and the best estimate of that difference is 18.64%
The test has statistical significance
```

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by mkleen** [comment]
Retest this please 

Test failure not related

KillIntegrationTest > testKillNonExisitingJob FAILED
    java.lang.AssertionError at [87B82E2923997A21:2145DB2CEB4E83BC]:0
## FAILURE: Test testKillSelectSysTable(io.crate.integrationtests.KillIntegrationTest)
java.lang.AssertionError: Query breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <644245L>
	at __randomizedtesting.SeedInfo.seed([87B82E2923997A21:8AFB2F8724719FDE]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$35(InternalTestCluster.java:2227)

REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=87B82E2923997A21 -Dtests.class=io.crate.integrationtests.KillIntegrationTest -Dtests.method="testKillNonExisitingJob" -Dtests.locale=ar-IQ -Dtests.timezone=Australia/Queensland

**Comment by mkleen** [comment]
retest this please 

KillIntegrationTest > testKillNonExisitingJob FAILED
    java.lang.AssertionError at [87B82E2923997A21:2145DB2CEB4E83BC]:0
## FAILURE: Test testKillSelectSysTable(io.crate.integrationtests.KillIntegrationTest)
java.lang.AssertionError: Query breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <644245L>
	at __randomizedtesting.SeedInfo.seed([87B82E2923997A21:8AFB2F8724719FDE]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$35(InternalTestCluster.java:2227)

REPRODUCE WITH: ./gradlew :server:test -Dtests.seed=87B82E2923997A21 -Dtests.class=io.crate.integrationtests.KillIntegrationTest -Dtests.method="testKillNonExisitingJob" -Dtests.locale=ar-IQ -Dtests.timezone=Australia/Queensland

File: server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java [hunk 1]
```diff
@@ -67,27 +71,59 @@
...
-    private void setNextDocId(LeafReaderContext readerContext, int doc) throws IOException {
+    private void setNextDocId(ReaderContext readerContext, int doc) throws IOException {
         for (LuceneCollectorExpression<?> e : collectorExpressions) {
             e.setNextReader(readerContext);
             e.setNextDocId(doc);
         }
     }
 
     public StreamBucket collect(IntContainer docIds) {
+        if (docIds.size() >= 10) {
```
Comment (mkleen) [inline server/src/main/java/io/crate/execution/engine/fetch/FetchCollector.java:82]: I experimented with smaller values as size theshold since the amount of doc ids can be less due to parallel fetch execution. However,  the performance goes worse with smaller batches.

File: server/src/main/java/org/elasticsearch/common/lucene/index/ElasticsearchLeafReader.java [hunk 2]
```diff
@@ -50,7 +52,7 @@ public ShardId shardId() {
     }
 
     @Override
-    public CacheHelper getCoreCacheHelper() {
+    public IndexReader.CacheHelper getCoreCacheHelper() {
```
Comment (seut) [inline server/src/main/java/org/elasticsearch/common/lucene/index/ElasticsearchLeafReader.java:55]: I wonder why this change is needed as the related ES commit does not change anything here?

**Review by seut — COMMENTED** [review]
Nice work 👍
Left 2 comments/suggestions.

**Review by seut — APPROVED** [review]
👍

**Comment by mfussenegger** [comment]
There are several places where the ReaderContext instances are created within a loop.  Couldn't they be created outside and reused per leaf?
