### PR TITLE
Fixed a race condition issue when accessing S3 repositories

### LINKED ISSUE #13743: Issues accessing repositories prevents retrieving snapshots from `sys.snapshots`
### CrateDB version

5.2.2, 5.2.6

### CrateDB setup information

Standard CrateDB Cloud cluster

### Problem description

If there is more than one repository configured in a cluster, and at least one of them has access issues (i.e. no longer valid credentials), the query to retrieve snapshots (`SELECT * FROM sys.snapshots`) becomes inconsistent and sometimes returns no results.

### Steps to Reproduce

1. Create two repositories
2. Perform some snapshots
3. Break auth to one of them

### Actual Result

`SELECT * FROM sys.snapshots` becomes inconsistent

### Expected Result

One of the repositories being unavailable does not impact retrieval of snapshots from others.

### PR DESCRIPTION
**Pull request by seut**
## Summary of the changes / Why this improves CrateDB
S3 clients are cached and reused to improve performance as such HTTP connection pools are used.
This will fix an existing race condition, a cached client could have changed after verifying it's cached settings, introduced by https://github.com/crate/crate/commit/7f1fb8713ac1ab02007b7635bef3b969022e525b

Additionally, this will (re-)introduce caching multiple different clients, just caching the actual used client may not result in wanted behaviour as the cache may overwritten immediately when accessing multiple repositories.

Fixes #13743.

### CODE REVIEW

**Comment by seut** [comment]
The current caching implementation will share S3 clients with identical settings even across repositories.
Another, probably less complex solution would be to not use a shared singleton `S3Service` instance, but create one instance per repository instead, similar to how #14152 implemented it for Azure repositories. WDYT?

**Comment by matriv** [comment]
With the current solution I think there is an issue, we synchronize only when we don't find a client for the given settings, to create a new one and put it into the hashmap, so if 2 threads come in, both don't find the client in the cache, then both (in series access) will create an instance and only the second one will be put in the cache. So I think we need to synchronize the whole block, I don't think this would have any perf impact on operations as the main time is spent on real work done by the client anyway.

Moreover, is: settings being updated for the same repo a valid point? If so, the we can potentially keep references in the hashmap (this new cache) forever, since settings are changed.

**Comment by seut** [comment]
> Moreover, is: settings being updated for the same repo a valid point? If so, the we can potentially keep references in the hashmap (this new cache) forever, since settings are changed.

Yes, but settings cannot be changed.

**Comment by matriv** [comment]
> The current caching implementation will share S3 clients with identical settings even across repositories. Another, probably less complex solution would be to not use a shared singleton `S3Service` instance, but create one instance per repository instead, similar to how #14152 implemented it for Azure repositories. WDYT?

My thinking about this, is that in this case the `AmazonS3Client` which will be used in prod, is much more heavy object compared to the Azure case, so I would say to keep it like this, with the cache instead.

File: plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java [hunk 1]
```diff
@@ -144,14 +145,11 @@ static AWSCredentialsProvider buildCredentials(Logger logger, S3ClientSettings c
...
     @Override
     public void close() {
-        synchronized (this) {
-            var localClientRef = clientCache;
-            if (localClientRef != null) {
-                localClientRef.decRef();
-            }
-            clientCache = null;
-            clientSettingsCache = null;
+        // the clients will shutdown when they will not be used anymore
```
Comment (matriv) [inline plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java:148]: It's edge case, but if a thread tries to access the cache, while the service is closing down, then we can run into issues, so I'd keep the synchronized also here.

**Review by matriv — APPROVED** [review]
LGTM, nice work with the test!

I left a comment though about `close()`.

File: plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java (hunk 1 above)
Comment (seut) [reply plugins/es-repository-s3/src/main/java/org/elasticsearch/repositories/s3/S3Service.java:148]: Good point, will do.
