### PR TITLE
Fix exception when using IN with _id in aggregations

### LINKED ISSUE #6564: Error when using IN with _id and aggregation
**CrateDB version**: 2.1.6 (can't test 2.2.x, maybe it's been fixed)

**JVM version**:

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**OS version / environment description**: Ubuntu 16.04 LTS

**Problem description**:

I get an error when using IN in combination with `_id` and aggregation/grouping:

```
SQLActionException[SQLParseException: invalid argument for ANY expression]
```

**Steps to reproduce**:

```
SELECT COUNT(*) FROM table WHERE _id IN ('some_id')
```

### PR DESCRIPTION
**Pull request by mxm**
Queries contaning _id values in in/any expressions where not correctly rewritten
by the `LuceneQueryBuilder`. We need to check if the passed Literal symbol is a collection.

This closes #6564.

### CODE REVIEW

**Comment by mxm** [comment]
Needs to be backported to `2.1` and `2.2`.

File: sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java [hunk 1]
```diff
@@ -1360,6 +1361,25 @@ private Function rewriteAndValidateFields(Function function, Context context) {
...
         }
 
+        /**
+         * Converts the Symbol value(s) to Lucene string(s) to match against the Lucene ids.
+         * @param symbol The Symbol to convert to a String uid.
+         * @return A literal holding the Lucene query value string.
+         */
+        private static Literal generateLuceneUIDs(Symbol symbol) {
+            if (DataTypes.isCollectionType(symbol.valueType())) {
+                List<String> strings = ValueSymbolVisitor.STRING_LIST.process(symbol);
```
Comment (chaudum) [inline sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: ValueSymbolVisitor is deprecated

File: CHANGES.txt [hunk 2]
```diff
@@ -107,6 +107,8 @@ Changes
 Fixes
 =====
 
+- Fix an exception which occurred when using row ids in IN or ANY queries.
```
Comment (chaudum) [inline CHANGES.txt]: our common way is to write **Fixed**

Comment (chaudum) [reply CHANGES.txt]: "row ids" may not be so clear what it is.
maybe say: ... when using the `_id` system column in `IN` and `ANY` queries. just a suggestion.

File: sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java (hunk 1 above)
Comment (mxm) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: If it's deprecated, it should be annotated as such. Where do you see deprecation?

Comment (chaudum) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: https://github.com/crate/crate/blob/a4dd6bd56f7ec37a4d2f13c553825abc87d45feb/sql/src/main/java/io/crate/analyze/symbol/ValueSymbolVisitor.java#L89-L105

Comment (mxm) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: Deprecation on a static field. I'd propagate the deprecated to the actual class. Or wait, is it just deprecated for string lists? why?

Comment (chaudum) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: it's for all public methods

Comment (mxm) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: I don't see any public methods inside `ValueSymbolVisitor` which are marked deprecated.

Comment (mxm) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: Ah, it **just** got deprecated. I'm based on the branch were it isn't. Would have come up during rebasing then.

Comment (mxm) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: https://github.com/crate/crate/pull/6576

Comment (mfussenegger) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: I think it would be okay to keep using the deprecated functionality for this PR - given that this is a fix and needs to be backported as well.

It will take a while until we can get rid of the `ValueSymbolVisitor` completely.
It's important that we don't introduce new features using the deprecated functionality, but I think for bugfixes it's fine.

Comment (mxm) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: I think this is a fair point. Actually not using the ValueSymbolVisitor also requires a bit more work (porting the existing functionality to the new base class); and this should be done also for other instances once we remove the ValueSymbolVisitor.

If you're ok with that, I'd keep it as-is, @chaudum.

Comment (chaudum) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: @mxm ok for me also

Comment (mxm) [reply sql/src/main/java/io/crate/lucene/LuceneQueryBuilder.java]: @chaudum Could you approve then?

**Comment by mxm** [comment]
Merged also to `2.1` and `2.2`.
