### PR TITLE
Fix REST bulk row count receiver when run with a single bulk arg

### LINKED ISSUE #16916: Nightly: `IndexOutOfBoundsException` when inserting a single record using the bulk interface
### CrateDB version

nightly, 5.10.0-SNAPSHOT, build 08d84f8, date 2024-10-29

### CrateDB setup information

Docker standard.
```
docker run --rm -it --publish=4200:4200 crate/crate:nightly -Cdiscovery.type=single-node
```

### Problem description

When using the bulk interface to insert a single record, CrateDB nightly [started failing on a downstream CI job](https://github.com/crate/cratedb-toolkit/actions/runs/11566597884/) 5 days ago. Maybe c7fb24dd is related?

- CrateDB Version:    version[5.10.0-SNAPSHOT], pid[1], build[08d84f8/NA]
- First Occurrence:   Tue, 29 Oct 2024 03:13:34 GMT

```sql
INSERT INTO t01 (name, value) VALUES (?, ?);
```
```
bulk_parameters=[('temperature', 42.42)]
```
When adding a second record, the procedure succeeds.
```
bulk_parameters=[('temperature', 42.42), ('humidity', 84.84)]
```

### Steps to Reproduce
```shell
pip install crate sqlparse
```
```python
"""
Error:              IndexOutOfBoundsException[Index: 1, Size: 1]
Problem:            ... when inserting a single record using the bulk interface.
CrateDB Version:    version[5.10.0-SNAPSHOT], pid[1], build[08d84f8/NA]
First Occurrence:   Tue, 29 Oct 2024 03:13:34 GMT

- https://github.com/crate/cratedb-toolkit/actions/runs/11566597884/job/32195528974#step:6:1362
- https://github.com/crate/cratedb-toolkit/actions/runs/11566597884/job/32195528974#step:14:16
"""
from pprint import pprint

import crate.client
import sqlparse


def insert_bulk():
    connection = crate.client.connect("http://localhost:4200/?schema=testdrive")

    # DDL.
    cursor = connection.cursor()
    for statement in sqlparse.parse("""
        DROP TABLE IF EXISTS t01;
        CREATE TABLE t01 (
            name STRING,
            value FLOAT
        );
        """):
        cursor.execute(str(statement))

    # DML.
    cursor.execute("""
    INSERT INTO t01 (name, value) VALUES (?, ?);
    """, bulk_parameters=[

        # Leave this alone to make it trip.
        ('temperature', 42.42),

        # Add this to make it work.
        # ('humidity', 84.84),
    ])

    cursor.close()
    connection.close()


if __name__ == "__main__":
    insert_bulk()
```

### Actual Result

```
crate.client.exceptions.ProgrammingError: IndexOutOfBoundsException[Index: 1, Size: 1]
```

### Expected Result

No error.

### References
- https://github.com/crate/cratedb-toolkit/actions/workflows/main.yml
- https://github.com/crate/cratedb-toolkit/actions/runs/11566597884/job/32195528974#step:6:1362
- https://github.com/crate/cratedb-toolkit/actions/runs/11566597884/job/32195528974#step:14:16

### PR DESCRIPTION
**Pull request by seut**
If only a single bulk arg is provided, we run the operation as a single execution instead of a bulk one. As failures result in an exception on single execution the given row will only contain one row count column.

This fix will not try to resolve the 2nd column when only one bulk arg (one result payload) is detected.

Follow up of https://github.com/crate/crate/commit/c7fb24dd00e0f14c8a2ab6f9c99ef5c663e85e8b.
Fixes #16916.

### CODE REVIEW

File: server/src/main/java/io/crate/rest/action/RestBulkRowCountReceiver.java [hunk 1]
```diff
@@ -43,7 +43,10 @@ class RestBulkRowCountReceiver extends BaseResultReceiver {
     @Override
     public void setNextRow(Row row) {
         rowCount = (long) row.get(0);
-        failure = (Throwable) row.get(1);
+        // Can be an optimized bulk request with only 1 bulk arg/operation which carries only 1 column (row count).
+        if (results.length > 1) {
+            failure = (Throwable) row.get(1);
+        }
```
Comment (seut) [inline server/src/main/java/io/crate/rest/action/RestBulkRowCountReceiver.java:49]: Instead of using the `result.length` as the detection, we could also use a `try/catch` block to catch possible IndexOutOfBoundsException`. The later maybe safer (we currently *expect*  this behaviour if the results length is 1), but afaik more expensive. WDYT?

Comment (mfussenegger) [reply server/src/main/java/io/crate/rest/action/RestBulkRowCountReceiver.java:49]: length check seems fine to me

**Review by mfussenegger — APPROVED** [review]
