### PR TITLE
Fixes primary key extraction if standalone booleans or parent columns are found

### LINKED ISSUE #18873: Unexpected ANTI JOIN Result
### CrateDB version

CrateDB 6.2.0-SNAPSHOT (built e4503a4)

### CrateDB setup information

Manual build following the tutorials: https://github.com/crate/crate/blob/master/devs/docs/basics.rst

### Problem description

Dear CrateDB Developers,
I have encountered an unexpected execution result and have prepared a reproducible case, which I’ve included below. I would greatly appreciate it if you could take a moment to review it.
```sql
CREATE  TABLE  t0(c0 BOOLEAN , c1 INT , c2 VARCHAR, PRIMARY KEY(c0));
INSERT INTO t0(c1, c0, c2) VALUES (-8, true, '1');
INSERT INTO t0(c1, c0) VALUES (1, false);
REFRESH TABLE t0;


SELECT * FROM t0 WHERE NOT EXISTS (SELECT 1 FROM (SELECT t0.c2 AS col0 FROM t0 WHERE t0.c0) AS sub0 WHERE ((t0.c0)OR(t0.c0)));
-- Wrong Execution Result: Empty Result
-- Expected Result: false, 1, NULL
```

### Steps to Reproduce

```sql
CREATE  TABLE  t0(c0 BOOLEAN , c1 INT , c2 VARCHAR, PRIMARY KEY(c0));
INSERT INTO t0(c1, c0, c2) VALUES (-8, true, '1');
INSERT INTO t0(c1, c0) VALUES (1, false);
REFRESH TABLE t0;


SELECT * FROM t0 WHERE NOT EXISTS (SELECT 1 FROM (SELECT t0.c2 AS col0 FROM t0 WHERE t0.c0) AS sub0 WHERE ((t0.c0)OR(t0.c0)));
-- Wrong Execution Result: Empty Result
-- Expected Result: false, 1, NULL
```

### Actual Result

```sql
Empty Result
```

### Expected Result

```sql
false, 1, NULL
```

### PR DESCRIPTION
**Pull request by seut**
See commits.
The second commit actually fixes #18873.

### CODE REVIEW

File: server/src/main/java/io/crate/analyze/where/EqualityExtractor.java [hunk 1]
```diff
@@ -499,17 +520,21 @@ public Symbol visitFunction(Function function, Context ctx) {
                     newArgs.add(arg.accept(this, ctx));
                     proxyBelowPost = ctx.proxyBelow || proxyBelowPost;
                 }
+
+                ctx.isUnderNotPredicate = prevIsUnderNotPredicate;
```
Comment (matriv) [inline server/src/main/java/io/crate/analyze/where/EqualityExtractor.java:524]: I don't have a concrete example that this can break, but I'm wondering if those should be done before the `switch(functionName)` as we call `arg.accept(this, ctx)` in the for loop.

**Review by matriv — APPROVED** [review]
look good, thx!
Left a question though, if you could double check the logic.

File: server/src/main/java/io/crate/analyze/where/EqualityExtractor.java (hunk 1 above)
Comment (seut) [reply server/src/main/java/io/crate/analyze/where/EqualityExtractor.java:524]: I had similar thoughts, but I just wanted to move their declaration to one place and not changing semantics. I'd have a look into this as a followup.
