### PR TITLE
fix NPE in the percentile aggregation function

### LINKED ISSUE #4353: Percentile throws NULLPOINTEREXCEPTION when not grouping by a column
Crate version: 0.56.3

This query throws a NULLPOINTEREXCEPTION
```
select percentile(field, 0.95) from table
```

This query does not
```
select percentile(field, 0.95), someOtherField from table group by someOtherField
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38859161-percentile-throws-nullpointerexception-when-not-grouping-by-a-column?utm_campaign=plugin&utm_content=tracker%2F505659&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F505659&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kovrus**
fixes #4353

### CODE REVIEW

**Comment by kovrus** [comment]
@dobe can you please review

File: sql/src/main/java/io/crate/operation/aggregation/impl/PercentileAggregation.java [hunk 1]
```diff
@@ -152,16 +144,4 @@ public Object terminatePartial(RamAccountingContext ramAccountingContext, TDiges
     public DataType partialType() {
         return TDigestStateType.INSTANCE;
     }
-
-    private static void validateFraction(double[] fractions) {
```
Comment (kovrus) [inline sql/src/main/java/io/crate/operation/aggregation/impl/PercentileAggregation.java]: removed because `state. quantile` does it

File: blackbox/docs/sql/aggregation.txt [hunk 2]
```diff
@@ -371,6 +371,9 @@ corresponding to the percentile of each fraction specified::
     SELECT 1 row in set (... sec)
 
 
+When a query with ``percentile`` function is issued against an empty table
+or it does not match any records in a table then a null result is returned.
```
Comment (dobe) [inline blackbox/docs/sql/aggregation.txt]: this is not table specific, this is about input rows. so i would explain it that way

File: sql/src/main/java/io/crate/operation/aggregation/impl/TDigestState.java [hunk 3]
```diff
@@ -70,4 +84,11 @@ public static TDigestState read(StreamInput in) throws IOException {
         return state;
     }
 
+    @Override
+    public void add(TDigest other) {
```
Comment (dobe) [inline sql/src/main/java/io/crate/operation/aggregation/impl/TDigestState.java]: why is this argument not a TDigestState?

File: sql/src/main/java/io/crate/operation/aggregation/impl/PercentileAggregation.java [hunk 4]
```diff
@@ -110,20 +104,18 @@ private TDigestState initState(Object argValue) {
 
     @Override
     public TDigestState reduce(RamAccountingContext ramAccountingContext, TDigestState state1, TDigestState state2) {
-        if (state1 == null) {
-            return state2;
-        }
-        if (state2 != null) {
+        if (state1.isEmpty()) {
             state1.add(state2);
```
Comment (dobe) [inline sql/src/main/java/io/crate/operation/aggregation/impl/PercentileAggregation.java]: why not use state2? i think the logic should stay as it was, just use isEmpty instead of then null check?

File: sql/src/main/java/io/crate/operation/aggregation/impl/TDigestState.java [hunk 5]
```diff
@@ -84,11 +83,8 @@ public static TDigestState read(StreamInput in) throws IOException {
         return state;
     }
 
-    @Override
-    public void add(TDigest other) {
+    public void add(TDigestState other) {
```
Comment (dobe) [inline sql/src/main/java/io/crate/operation/aggregation/impl/TDigestState.java]: now actually this override is not required anymore now

Comment (kovrus) [inline sql/src/main/java/io/crate/operation/aggregation/impl/TDigestState.java]: it is different methods signatures, you cannot override 
 public void add(TDigest other) 
with 
 public void add(TDigestState other)

Comment (kovrus) [inline sql/src/main/java/io/crate/operation/aggregation/impl/TDigestState.java]: there is no method ``public void add(TDigestState other)`` in AVLTreeDigest
