### PR TITLE
Fix an issue with switching to plaintext

### LINKED ISSUE #11954: Switching to plaintext doesn't seem to work occasionally
related to https://github.com/crate/crate/issues/11546 - not yet released, has a bug caught by tests (occasionally flaky).

### CrateDB version

current master

### Steps to Reproduce

run test `io.crate.integrationtests.SSLTrustedZoneITest.test_switch_to_plaintext_enabled_downgrades_to_plaintext`
with options 
`-Dtests.seed=609F887A9B59B7F6 -Dtests.nightly=true -Dtests.locale="kl-Latn-GL" -Dtests.timezone=Australia/Sydney`

**another way to reproduce, proving that's it's bug**
completely remove body of the test and run empty test with the seed specified above - it fails with the same error.

test passes if I comment out [this line](https://github.com/crate/crate/blob/d2518c0aec42975b398e6a93eee9f450ea0027c2/server/src/main/java/org/elasticsearch/transport/netty4/HostBasedAuthHandler.java#L94) i.e down't downgrade and imitate normal behaviour without this feature.

### Expected Result

test passes 

### Actual Result

```
at __randomizedtesting.SeedInfo.seed([609F887A9B59B7F6:CD3ED7167BEF6B6B]:0)
	at java.base@17/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
	at java.base@17/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:715)
	at java.base@17/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1047)
	at app//org.elasticsearch.common.util.concurrent.BaseFuture$Sync.get(BaseFuture.java:251)
	at app//org.elasticsearch.common.util.concurrent.BaseFuture.get(BaseFuture.java:86)
	at app//org.elasticsearch.common.util.concurrent.FutureUtils.get(FutureUtils.java:57)
	at app//org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:34)
	at app//org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:423)
	at app//org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:1279)
```

### PR DESCRIPTION
**Pull request by BaurzhanSakhariev**
Resolves #11954 by using https://netty.io/4.1/api/io/netty/handler/ssl/SslHandler.html#closeOutbound-- on the server side

`sslCloseFuture()` is used on the client side - it gets notified if the inbound of the SSLEngine is closed.

## Checklist

 - [ ] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [ ] Touched code is covered by tests
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [ ] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Review by seut — APPROVED** [review]
nice, lgtm.

**Comment by BaurzhanSakhariev** [comment]
Hi @seut, I updated test and also added a bit of logging to the client side

File: server/src/test/java/io/crate/integrationtests/SSLTrustedZoneITest.java [hunk 1]
```diff
@@ -70,30 +69,25 @@ protected Settings nodeSettings(int nodeOrdinal) {
...
+        // Node 1 has default value "false" for switch_to_plaintext
         return commonSettings.build();
     }
 
 
-
     @Test
-    @AwaitsFix(bugUrl = "https://github.com/crate/crate/issues/11954")
     public void test_switch_to_plaintext_enabled_downgrades_to_plaintext() throws Exception {
+        internalCluster().startNodes(2);
```
Comment (seut) [inline server/src/test/java/io/crate/integrationtests/SSLTrustedZoneITest.java:82]:
```suggestion
        // As soon as the cluster is started, the node will start communicating and downgrading to plaintext.
        // Thus we start the nodes manually in order to just fail this test case and not the suite in case of errors.
        internalCluster().startNodes(2);
```

**Review by seut — APPROVED** [review]
I've added a suggestion for a comment, otherwise all looks fine
