### PR TITLE
validate the source data of COPY-FROM

### LINKED ISSUE #10186: "COPY FROM" is bypassing type validation
**CrateDB version**:
4.1.7

**Environment description**:

 - local CrateDB instance
 - Number of nodes: 1

**Problem description**:

By inserting data with `COPY FROM ...` from S3 it is possible to write string values (tested with empty strings) into boolean columns. By querying such data `SQLActionException[SQLParseException: Can't convert "" to boolean]` is returned. I haven't tested this issue with different types or different values.

**Steps to reproduce**:

```
# run crate
docker run -ti --rm -p 4200:4200 crate:4.1.7

# create a table with a boolean column
create table x (y boolean);

# create a json file to be imported inside the container. Note the string value
echo '{"y": ""}' > /tmp/x.json

# import that file
COPY x FROM 'file:///tmp/x.json';

# Try to query the data
select * from x
```

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
resolves #10186 

The scope here is that given key-value pairs of the raw data, and `tableInfo`, to validate the raw data against the corresponding columns' `dataType`. Therefore, input formats such as csv or validating raw data that fall into dynamically added columns are not the concern. 

Also,
```sql
#fixes a bug
create table tbl (id text default gen_random_text_uuid(), x int) clustered into 1 shards;
echo -e '{"x":123}\n{"x":123}' > /tmp/t.json

cr> copy tbl from '/tmp/t.json' return summary;
+-------------------------------------------------------+--------------------+---------------+-------------+--------+
| node                                                  | uri                | success_count | error_count | errors |
+-------------------------------------------------------+--------------------+---------------+-------------+--------+
| {"id": "FCDU_8yDRX2D1glDktsJog", "name": "Schenadüi"} | file:///tmp/t.json |             2 |           0 | {}     |
+-------------------------------------------------------+--------------------+---------------+-------------+--------+
COPY 1 row in set (0.092 sec)

cr> select * from tbl;
+----------------------+-----+
| id                   |   x |
+----------------------+-----+
| 5RsVI38BtyeSIGv4rYgT | 123 |
| 5RsVI38BtyeSIGv4rYgT | 123 |  # <----- second uuid should be not the same as the first
+----------------------+-----+
SELECT 2 rows in set (0.787 sec)
```

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

**Comment by jeeminso** [comment]
Hello @mfussenegger, the initial draft should be done, could you have a quick look at the overall direction? I am about to move onto writing tests and iterate. Thanks!

**Comment by BaurzhanSakhariev** [comment]
could you compare it with current master in terms of performance penalty for validation? If it's notable, we might create another follow up issue to make validation optional via flag.

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java [hunk 1]
```diff
@@ -21,27 +21,148 @@
...
+                new BytesArray(src).array());
+            parsed = parser.map();
+            if (parser.getTokenLocation().columnNumber < src.length()) {
+                throw new IllegalArgumentException("failed to parse `" + src.substring(parser.getTokenLocation().columnNumber) + "`");
+            }
+        } catch (IOException e) {
+            if (e instanceof JsonParseException) {
+                throw new IllegalArgumentException("failed to parse");
+            }
+        }
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java:93]: This would ignore other types of IOException - shouldn't they bubble up?
And why does it re-raise the JsonParseException? I suspect the original exception would have a more informative error message.

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java [hunk 2]
```diff
@@ -21,27 +21,148 @@
...
+                      // evaluateDefaultValues is invoked per row for expressions like now(), and gen_random_text_uuid().
+                      // Other deterministic expressions like abs(-10) should have been evaluated once and for all by the analyzer.
+                      evaluateDefaultValues(table.defaultExpressionColumns(), txnCtx, nodeCtx));
+
+        GeneratedColumns<Map<String, Object>> generatedColumns = new GeneratedColumns<>(
+            inputFactory,
+            txnCtx,
+            FromSourceRefResolver.WITHOUT_PARTITIONED_BY_REFS,
+            refLookUpCache.values(),
+            table.generatedColumns());
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java:106]: Is it possible to do this once in the constructor instead of per row?

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java [hunk 3]
```diff
@@ -21,27 +21,148 @@
...
+            var column = reference.column();
+            Maps.mergeInto(validatedSource, column.name(), column.path(), valueForInsert);
+        }
+
+        checks.validate(validatedSource);
+
+        return validatedSource;
+    }
+
+    private Map<String, Object> validateRawSource(Map<String, Object> rawSource) {
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java:126]: would it be possible to do the validation in parsing in one pass using the parser/token API?
Would avoid creating a map twice.

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java [hunk 4]
```diff
@@ -21,27 +21,148 @@
...
+            String srcCol = entry.getKey();
+            Object data = entry.getValue();
+            Reference ref = refLookUpCache.get(srcCol);
+            if (ref == null) {
+                try {
+                    ref = table.resolveColumn(srcCol, true, txnCtx.sessionSettings().errorOnUnknownObjectKey());
+                } catch (ColumnUnknownException e) {
+                    // This handles unknown columns of strict tables and tables only.
+                    // Unknown subcolumns of strict objects will be created here and the validation happens at DocumentMapper
+                    throw new StrictDynamicMappingException(table.ident().toString(), srcCol);
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java:138]: Not sure I understand this comment. If the `column_policy` is strict, implicit dynamic column creation should be prohibited. 
Shouldn't we let the original `ColumnUnknownException` bubble up?

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java (hunk 1 above)
Comment (jeeminso) [reply server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java:93]: Thank you, I should have re-thrown for the rest of IOExceptions. For JsonParseException, I was trying to make the messages more consistent. Also, the original message had a bit too much,

```
cr> copy e1 from '/tmp/t.json' return summary;
+---------------------------------------------------------+--------------------+---------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| node                                                    | uri                | success_count | error_count | errors                                                                                                                                                                                                                                                                        |
+---------------------------------------------------------+--------------------+---------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| {"id": "AA-O2L6hTg272-WfB1cjkQ", "name": "Tiejer Flue"} | file:///tmp/t.json |             0 |           1 | {"com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code 125)): expected a value\n at [Source: (byte[])\"{\"a\":}\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\"; line: 1, column: 7]": {"count": 1, "line_numbers": [1]}} |
+---------------------------------------------------------+--------------------+---------------+-------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

Comment (jeeminso) [reply server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java]: Please check 5a7acee for updates

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java (hunk 3 above)
Comment (jeeminso) [reply server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java]: Please check a122c6a for updates, I tried to reuse but modify ES code as least as possible.

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java (hunk 2 above)
Comment (jeeminso) [reply server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java]: I do not think it is possible, since the 4th parameter represents all present columns for that row at that instant.

**Comment by jeeminso** [comment]
sorry @mfussenegger, it is not ready for review. In some cases exceptions are lost and the program hangs.

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java (hunk 3 above)
Comment (mfussenegger) [reply server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java]: You could also have a look at the `SourceParser` which does something similar. (But also supports skipping columns it doesn't need)

Comment (jeeminso) [reply server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java]: I have checked `SourceParser` but it involves several nullchecks for dataTypes and requiredColumns. And if I were to have a version with the nullchecks removed, and add a step for validation, it will end up similar to https://github.com/crate/crate/commit/a122c6a2f1828b4bc3028c5f607c693fc8f1d043. 
Should I try to copy over the logic similar to `SourceParser`?

**Comment by jeeminso** [comment]
The implementation is nearly complete, I collected below measurements to help the decision on supporting a disable flag.


## Performance Measurements

First with the simplest possible,
```
$ cat specs/sql/raw_insert_simple.sql 
create table raw_insert_simple (x integer) clustered into 1 shards with(number_of_replicas='0');
```
```
$ cat specs/raw_insert_simple.toml 
[setup]
statement_files = ["sql/raw_insert_simple.sql"]
statements = [
    "refresh table raw_insert_simple"
]

[[queries]]
name = "raw_insert_simple"
statement = "copy raw_insert_simple from 'specs/data/raw_insert_simple.json'"
concurrency = 1
iterations = 10

[teardown]
statements = ["drop table raw_insert_simple"]
```
```
$ tail specs/data/raw_insert_simple.json // x from 1 to 1M
{x:999991}
{x:999992}
{x:999993}
{x:999994}
{x:999995}
{x:999996}
{x:999997}
{x:999998}
{x:999999}
{x:1000000}

```


Results:
```
# Results (server side duration in ms)
V1: 4.8.0-826ebe6188e1e44a21796632f0346d7374c1743e
V2: 4.8.0-78ca377f81606acaf70982a108d2461dcf6d6af5

Q: copy raw_insert_simple from 'specs/data/raw_insert_simple.json'
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |     1454.014 ±  179.066 |   1344.015 |   1406.926 |   1426.062 |   1957.925 |
|   V2    |     1703.013 ±  167.299 |   1562.466 |   1661.275 |   1697.381 |   2163.592 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +  15.77%                           +  16.58%   
There is a 99.52% probability that the observed difference is not random, and the best estimate of that difference is 15.77%
The test has statistical significance


System/JVM Metrics (durations in ms, byte-values in MB)
    |    YOUNG GC            |       OLD GC           |      HEAP         |     ALLOC     
    |  cnt      avg      max |  cnt      avg      max |  initial     used |     rate      total
 V1 |   53    23.40    38.49 |    0     0.00     0.00 |      268      274 |     0.00          0
 V2 |   57    26.82    34.74 |    0     0.00     0.00 |      268     1990 |     0.00          0
    
V1 top allocation frames
  TransportShardUpsertAction.insert(...):155
  DocumentParser.isEmptyDoc(...):109
  TransportShardUpsertAction.processRequestItems(...):100
  Base64$Encoder.encode(byte[]):41
  Murmur3HashFunction.hash(String):38
V2 top allocation frames
  TransportShardUpsertAction.processRequestItems(...):122
  FromRawInsertSource.generateSourceAndCheckConstraints(Object[]):120
  StringLatin1.replace(...):46
  BufferedReader.readLine(...):35
  UnicodeUtil.UTF8toUTF16(...):33

```
Show that ~15% slower with the validations compared to master.


Now involving a default column and a generated column,
```
$ cat specs/sql/raw_insert.sql 
create table raw_insert (id text default ('text!'), x integer, y double generated always as(x + 1)) clustered into 1 shards with(number_of_replicas='0');
```
again copying x from 1 to 1M.

Results:
```
# Results (server side duration in ms)
V1: 4.8.0-826ebe6188e1e44a21796632f0346d7374c1743e
V2: 4.8.0-78ca377f81606acaf70982a108d2461dcf6d6af5

Q: copy raw_insert from '/home/jee/crate/crate-benchmarks/specs/data/raw_insert.json'
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |     2520.630 ±  179.105 |   2435.121 |   2459.602 |   2490.844 |   3026.635 |
|   V2    |     1735.307 ±  149.219 |   1625.159 |   1680.247 |   1744.461 |   2136.863 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -  36.90%                           -  37.65%   
There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 36.90%
The test has statistical significance


System/JVM Metrics (durations in ms, byte-values in MB)
    |    YOUNG GC            |       OLD GC           |      HEAP         |     ALLOC     
    |  cnt      avg      max |  cnt      avg      max |  initial     used |     rate      total
 V1 |   94    29.11    32.84 |    0     0.00     0.00 |      268      583 |     0.00          0
 V2 |   59    27.03    25.39 |    0     0.00     0.00 |      268      715 |     0.00          0
    
V1 top allocation frames
  TransportShardUpsertAction.processRequestItems(...):947
  AbstractBytesReference$MarkSupportingStreamInputWrapper.read(...):557
  JsonXContentParser.nextToken():131
  XContentHelper.toMap(...):128
  Formatter.parse(String):77
V2 top allocation frames
  FromRawInsertSource.generateSourceAndCheckConstraints(Object[]):127
  UTF8StreamJsonParser.nextToken():126
  TransportShardUpsertAction.processRequestItems(...):100
  StringLatin1.replace(...):50
  BufferedReader.readLine(...):40

```

Actually shows ~35% faster compared to master.

**Comment by jeeminso** [comment]
The implementation is nearly complete, I collected below measurements to help the decision on supporting a disable flag.


## Performance Measurements

First with the simplest possible,
```
$ cat specs/sql/raw_insert_simple.sql 
create table raw_insert_simple (x integer) clustered into 1 shards with(number_of_replicas='0');
```
```
$ cat specs/raw_insert_simple.toml 
[setup]
statement_files = ["sql/raw_insert_simple.sql"]
statements = [
    "refresh table raw_insert_simple"
]

[[queries]]
name = "raw_insert_simple"
statement = "copy raw_insert_simple from 'specs/data/raw_insert_simple.json'"
concurrency = 1
iterations = 10

[teardown]
statements = ["drop table raw_insert_simple"]
```
```
$ tail specs/data/raw_insert_simple.json // x from 1 to 1M
{x:999991}
{x:999992}
{x:999993}
{x:999994}
{x:999995}
{x:999996}
{x:999997}
{x:999998}
{x:999999}
{x:1000000}

```


Results:
```
# Results (server side duration in ms)
V1: 4.8.0-826ebe6188e1e44a21796632f0346d7374c1743e
V2: 4.8.0-78ca377f81606acaf70982a108d2461dcf6d6af5

Q: copy raw_insert_simple from 'specs/data/raw_insert_simple.json'
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |     1454.014 ±  179.066 |   1344.015 |   1406.926 |   1426.062 |   1957.925 |
|   V2    |     1703.013 ±  167.299 |   1562.466 |   1661.275 |   1697.381 |   2163.592 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +  15.77%                           +  16.58%   
There is a 99.52% probability that the observed difference is not random, and the best estimate of that difference is 15.77%
The test has statistical significance


System/JVM Metrics (durations in ms, byte-values in MB)
    |    YOUNG GC            |       OLD GC           |      HEAP         |     ALLOC     
    |  cnt      avg      max |  cnt      avg      max |  initial     used |     rate      total
 V1 |   53    23.40    38.49 |    0     0.00     0.00 |      268      274 |     0.00          0
 V2 |   57    26.82    34.74 |    0     0.00     0.00 |      268     1990 |     0.00          0
    
V1 top allocation frames
  TransportShardUpsertAction.insert(...):155
  DocumentParser.isEmptyDoc(...):109
  TransportShardUpsertAction.processRequestItems(...):100
  Base64$Encoder.encode(byte[]):41
  Murmur3HashFunction.hash(String):38
V2 top allocation frames
  TransportShardUpsertAction.processRequestItems(...):122
  FromRawInsertSource.generateSourceAndCheckConstraints(Object[]):120
  StringLatin1.replace(...):46
  BufferedReader.readLine(...):35
  UnicodeUtil.UTF8toUTF16(...):33

```
Show that ~15% slower with the validations compared to master.


Now involving a default column and a generated column,
```
$ cat specs/sql/raw_insert.sql 
create table raw_insert (id text default ('text!'), x integer, y double generated always as(x + 1)) clustered into 1 shards with(number_of_replicas='0');
```
again copying x from 1 to 1M.

Results:
```
# Results (server side duration in ms)
V1: 4.8.0-826ebe6188e1e44a21796632f0346d7374c1743e
V2: 4.8.0-78ca377f81606acaf70982a108d2461dcf6d6af5

Q: copy raw_insert from 'specs/data/raw_insert.json'
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |     2520.630 ±  179.105 |   2435.121 |   2459.602 |   2490.844 |   3026.635 |
|   V2    |     1735.307 ±  149.219 |   1625.159 |   1680.247 |   1744.461 |   2136.863 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               -  36.90%                           -  37.65%   
There is a 100.00% probability that the observed difference is not random, and the best estimate of that difference is 36.90%
The test has statistical significance


System/JVM Metrics (durations in ms, byte-values in MB)
    |    YOUNG GC            |       OLD GC           |      HEAP         |     ALLOC     
    |  cnt      avg      max |  cnt      avg      max |  initial     used |     rate      total
 V1 |   94    29.11    32.84 |    0     0.00     0.00 |      268      583 |     0.00          0
 V2 |   59    27.03    25.39 |    0     0.00     0.00 |      268      715 |     0.00          0
    
V1 top allocation frames
  TransportShardUpsertAction.processRequestItems(...):947
  AbstractBytesReference$MarkSupportingStreamInputWrapper.read(...):557
  JsonXContentParser.nextToken():131
  XContentHelper.toMap(...):128
  Formatter.parse(String):77
V2 top allocation frames
  FromRawInsertSource.generateSourceAndCheckConstraints(Object[]):127
  UTF8StreamJsonParser.nextToken():126
  TransportShardUpsertAction.processRequestItems(...):100
  StringLatin1.replace(...):50
  BufferedReader.readLine(...):40

```

Actually shows ~35% faster compared to master.

**Comment by jeeminso** [comment]
It was expected that copies to tables without generated, default columns to have the most performance impact. I tried to narrow down the exact cause of the degradation and it looks like parsing of the data to `Map` took up the most.

There will be a clear gain if we do support a disable validation flag but it will only be useful to the tables without generated columns and default expressions.

**Comment by jeeminso** [comment]
Hi @mfussenegger, this should be ready for review now. Thank you!

File: server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java [hunk 5]
```diff
@@ -21,27 +21,177 @@
...
+    @Override
+    public Object validate(String field, Object data) {
+        Reference ref = refLookUpCache.get(field);
+        if (ref == null) {
+            try {
+                ref = table.resolveColumn(field, true, txnCtx.sessionSettings().errorOnUnknownObjectKey());
+            } catch (ColumnUnknownException e) {
+                refLookUpCache.presentColumns(); // clear presentColumns
+                // This handles unknown columns of strict tables.
+                // Whereas unknown subcolumns of strict objects will be create here but its validations will happen at DocumentMapper
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/dml/upsert/FromRawInsertSource.java:135]:
```suggestion
                // Re-raise as StrictDynamicMappingException to ensure this code path uses the same exception as the DocumentMapper does
```

File: server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java [hunk 6]
```diff
@@ -118,7 +116,6 @@ public ShardUpsertRequest(StreamInput in) throws IOException {
         }
         continueOnError = in.readBoolean();
         duplicateKeyAction = DuplicateKeyAction.values()[in.readVInt()];
-        validateConstraints = in.readBoolean();
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java:121]: We need to keep reading the boolean for older versions for streaming BWC

File: server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java [hunk 7]
```diff
@@ -167,7 +164,6 @@ public void writeTo(StreamOutput out) throws IOException {
 
         out.writeBoolean(continueOnError);
         out.writeVInt(duplicateKeyAction.ordinal());
-        out.writeBoolean(validateConstraints);
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java:170]: See previous comment

File: server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java (hunk 6 above)
Comment (jeeminso) [reply server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java:121]: Thank you!

File: libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/support/XContentCustomValidator.java [hunk 8]
```diff
@@ -0,0 +1,61 @@
...
+
+import static org.elasticsearch.common.xcontent.support.AbstractXContentParser.SIMPLE_MAP_FACTORY;
+import static org.elasticsearch.common.xcontent.support.AbstractXContentParser.readValue;
+
+import java.io.IOException;
+import java.util.Map;
+
+import org.elasticsearch.common.xcontent.XContentParser;
+
+public class XContentCustomValidator {
```
[the remark this answers is not in the document]
Comment (jeeminso) [reply libs/es-x-content/src/main/java/org/elasticsearch/common/xcontent/support/XContentCustomValidator.java:32]: Thanks `ParameterizedXContentParser` seems to be the best

File: server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java (hunk 6 above)
Comment (jeeminso) [reply server/src/main/java/io/crate/execution/dml/upsert/ShardUpsertRequest.java:121]: Actually, just realized that I should not remove `validateConstraints` at all, was confused with the disable flag discussed.. Dropping the changeset.

**Comment by jeeminso** [comment]
retest this please

**Review by mfussenegger — APPROVED** [review]
