### PR TITLE
bug: when both ignore-nulls option and order-by (window order clause) are specified

### LINKED ISSUE #11645: IGNORE NULL option in window functions behaves incorrectly
### CrateDB version

4.7.0 -SNAPSHOT-d872104

### CrateDB setup information

_No response_

### Steps to Reproduce

```sql
CREATE TABLE test (a integer);
INSERT INTO test (a) VALUES (1), (2), (3), (4), (5);
```

Given the following query with `LEAD RESPECT NULLS`:
```sql
SELECT a, LEAD(a) RESPECT NULLS OVER (ORDER BY a)
FROM test
ORDER BY a
```
returns:
```
+---+---------------------------------------------+
| a | lead(a) RESPECT NULLS OVER (ORDER BY a ASC) |
+---+---------------------------------------------+
| 1 |                                           2 |
| 2 |                                           3 |
| 3 |                                           4 |
| 4 |                                           5 |
| 5 |                                        NULL |
+---+---------------------------------------------+
```

The same query with `IGNORE NULLS`:
```sql
SELECT a, LEAD(a) IGNORE NULLS OVER (ORDER BY a)
FROM test
ORDER BY a
```
returns:
```
+---+--------------------------------------------+
| a | lead(a) IGNORE NULLS OVER (ORDER BY a ASC) |
+---+--------------------------------------------+
| 1 |                                          2 |
| 2 |                                       NULL |
| 3 |                                          4 |
| 4 |                                       NULL |
| 5 |                                       NULL |
+---+--------------------------------------------+
```

### Expected Result

The result set of both queries is identical.

### Actual Result

The result set differs, there are unexpected `null` values produced by `LEAD IGNORE NULLS`.

### PR DESCRIPTION
**Pull request by jeeminso**
## Summary of the changes / Why this improves CrateDB
bug fix, fixes #11645

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [ ] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

File: server/src/main/java/io/crate/execution/engine/window/WindowFrameState.java [hunk 1]
```diff
@@ -49,6 +49,10 @@ public int upperBoundExclusive() {
         return upperBoundExclusive;
     }
 
+    public int partitionEnd() {
```
Comment (jeeminso) [inline server/src/main/java/io/crate/execution/engine/window/WindowFrameState.java:52]: `WindowFrameState` implementation assumes direct access as the only usage by utilizing `getRowInFrameAtIndexOrNull` or `getRowInPartitionAtIndexOrNull`. But with `ignore nulls` option introduced, sequential accesses are required (to search for non-null elements) and need `partitionEnd` for that.

Comment (jeeminso) [reply server/src/main/java/io/crate/execution/engine/window/WindowFrameState.java:52]: since `lead/lag` should not be bounded by window definitions, `upperBoundExclusive()` or `size()` are not feasible.

**Review by seut — COMMENTED** [review]
Looks good, but missing a CHANGES entry ;)

**Comment by jeeminso** [comment]
@seut Thank you! added the entry

**Review by seut — APPROVED** [review]
👍
