### PR TITLE
Ensure correct order of hash symbols used in HashJoin plans

### LINKED ISSUE #14583: Optimizer seems to be breaking queries
### CrateDB version

5.4.0

### CrateDB setup information

_No response_

### Problem description

This query:
```sql
SELECT core.clusters.* FROM 
  core.subscriptions
  JOIN core.consumption_report ON core.subscriptions.reference = core.consumption_report.subscription_id 
  JOIN core.clusters ON core.subscriptions.id = core.clusters.subscription_id
  JOIN core.cluster_billing_info ON core.cluster_billing_info.cluster_id = core.clusters.id AND core.cluster_billing_info.kind = core.consumption_report.kind 
WHERE 
  core.consumption_report.reporting_id IS NULL 
  AND core.consumption_report.from_ts >= core.subscriptions.dc['created'] 
  AND core.consumption_report.cluster_id = core.clusters.id 
  AND core.subscriptions.provider = 'STRIPE' 
ORDER BY core.subscriptions.id, core.consumption_report.to_ts limit 100;
```

Results in two different execution plans depending on whether statistics are available.

**When stats are not available, the query works**:
```sql
Eval[id, name, username, dc, num_nodes, hardware_specs, crate_version, project_id, product_name, product_tier, product_unit, channel, origin, is_deleted, cluster_version, subscription_id, external_ip, deletion_protected, ip_whitelist, status, last_seen, suspended, backup_schedule] (rows=100)
  └ Fetch[id, reference, dc['created'], to_ts, subscription_id, kind, from_ts, cluster_id, id, name, username, dc, num_nodes, hardware_specs, crate_version, project_id, product_name, product_tier, product_unit, channel, origin, is_deleted, cluster_version, subscription_id, external_ip, deletion_protected, ip_whitelist, status, last_seen, suspended, backup_schedule, cluster_id, kind] (rows=100)
    └ Limit[100::bigint;0] (rows=100)
      └ OrderBy[id ASC to_ts ASC] (rows=unknown)
        └ HashJoin[((cluster_id = id) AND (kind = kind))] (rows=unknown)
          ├ HashJoin[((id = subscription_id) AND (cluster_id = id))] (rows=unknown)
          │  ├ HashJoin[((reference = subscription_id) AND (from_ts >= dc['created']))] (rows=unknown)
          │  │  ├ Collect[core.subscriptions | [id, reference, dc['created']] | (provider = 'STRIPE')] (rows=unknown)
          │  │  └ Collect[core.consumption_report | [to_ts, subscription_id, kind, from_ts, cluster_id] | (reporting_id IS NULL)] (rows=unknown)
          │  └ Collect[core.clusters | [_fetchid, id, subscription_id] | true] (rows=unknown)
          └ Collect[core.cluster_billing_info | [cluster_id, kind] | true] (rows=unknown)
```

**When stats are available, the query does not work**:
```sql
Eval[id, name, username, dc, num_nodes, hardware_specs, crate_version, project_id, product_name, product_tier, product_unit, channel, origin, is_deleted, cluster_version, subscription_id, external_ip, deletion_protected, ip_whitelist, status, last_seen, suspended, backup_schedule] (rows=100)
  └ Fetch[id, name, username, dc, num_nodes, hardware_specs, crate_version, project_id, product_name, product_tier, product_unit, channel, origin, is_deleted, cluster_version, subscription_id, external_ip, deletion_protected, ip_whitelist, status, last_seen, suspended, backup_schedule, id, to_ts] (rows=100)
    └ Limit[100::bigint;0] (rows=100)
      └ OrderBy[id ASC to_ts ASC] (rows=0)
        └ Eval[_fetchid, id, subscription_id, id, to_ts] (rows=0)
          └ HashJoin[((cluster_id = id) AND (kind = kind))] (rows=0)
            ├ Collect[core.cluster_billing_info | [cluster_id, kind] | true] (rows=2724)
            └ Eval[_fetchid, id, subscription_id, id, to_ts, kind] (rows=0)
              └ HashJoin[((id = subscription_id) AND (cluster_id = id))] (rows=0)
                ├ Collect[core.clusters | [_fetchid, id, subscription_id] | true] (rows=2345)
                └ Eval[id, to_ts, kind, cluster_id] (rows=47)
                  └ HashJoin[((reference = subscription_id) AND (from_ts >= dc['created']))] (rows=47)
                    ├ Collect[core.consumption_report | [to_ts, subscription_id, kind, from_ts, cluster_id] | (reporting_id IS NULL)] (rows=37626)
                    └ Collect[core.subscriptions | [id, reference, dc['created']] | (provider = 'STRIPE')] (rows=1299)
```

### Steps to Reproduce

Please get in touch privately for test data

### Actual Result

Nothing returned

### Expected Result

Rows should have been returned

### PR DESCRIPTION
**Pull request by seut**
The hash symbols extracted from the join condition must stay in the same order for both, left and right inputs to generate a matching hash code (used for matching the rows).
In this case, the symbols were mixed up as they were processed based on unordered relation names.
    
Fixes #14583.

### CODE REVIEW

File: server/src/main/java/io/crate/planner/operators/HashJoin.java [hunk 1]
```diff
@@ -99,21 +99,34 @@ public ExecutionPlan build(DependencyCarrier executor,
...
         var lhsHashSymbols = new ArrayList<Symbol>();
-        for (var symbols : hashSymbols.values()) {
+        var rightRelationNames = rhs.getRelationNames();
+        for (var entry : hashSymbols.entrySet()) {
+            var relationName = entry.getKey();
+            var symbols = entry.getValue();
+            if (symbols == null) {
+                continue;
+            }
+            var symbolConsumer = lhsHashSymbols;
```
Comment (mkleen) [inline server/src/main/java/io/crate/planner/operators/HashJoin.java:124]: I would prefer to not use a swapping variable in a loop if it can be avoided.

Comment (seut) [reply server/src/main/java/io/crate/planner/operators/HashJoin.java:124]: why? the var is reset in each iteration.

Comment (mkleen) [reply server/src/main/java/io/crate/planner/operators/HashJoin.java:124]: I think this is easier to read:

```
        var rhsHashSymbols = new ArrayList<Symbol>();
        var lhsHashSymbols = new ArrayList<Symbol>();
        var rightRelationNames = rhs.getRelationNames();
        for (var entry : hashSymbols.entrySet()) {
            var relationName = entry.getKey();
            var symbols = entry.getValue();
            if (symbols == null) {
                continue;
            }
            if (rightRelationNames.contains(relationName)) {
                for (Symbol symbol : symbols) {
                    rhsHashSymbols.add(paramBinder.apply(symbol));
                }
            } else {
                for (Symbol symbol : symbols) {
                    lhsHashSymbols.add(paramBinder.apply(symbol));
                }
            }
        }
```

Comment (mkleen) [reply server/src/main/java/io/crate/planner/operators/HashJoin.java:124]: However, its a personal preference and minor.

**Review by mkleen — APPROVED** [review]
We should probably backport this. The problem can also occur without the newly introduced join swap rule.

File: server/src/main/java/io/crate/planner/operators/HashJoin.java (hunk 1 above)
Comment (mkleen) [reply server/src/main/java/io/crate/planner/operators/HashJoin.java:124]: Actually, to make the code more resilient I would probably go for this version, to make sure the hash symbols on each side really belong there.

```
        var rhsHashSymbols = new ArrayList<Symbol>();
        var lhsHashSymbols = new ArrayList<Symbol>();
        var rightRelationNames = rhs.getRelationNames();
        var leftRelationNames = lhs.getRelationNames();
        for (var entry : hashSymbols.entrySet()) {
            var relationName = entry.getKey();
            var symbols = entry.getValue();
            if (symbols == null) {
                continue;
            }
            if (rightRelationNames.contains(relationName)) {
                for (Symbol symbol : symbols) {
                    rhsHashSymbols.add(paramBinder.apply(symbol));
                }
            if (leftRelationNames.contains(relationName)) {
                for (Symbol symbol : symbols) {
                    lhsHashSymbols.add(paramBinder.apply(symbol));
                }
            }
        }
```

**Review by BaurzhanSakhariev — APPROVED** [review]

File: docs/appendices/release-notes/5.4.3.rst [hunk 2]
```diff
@@ -46,4 +46,6 @@ See the :ref:`version_5.4.0` release notes for a full list of changes in the
 Fixes
 =====
 
-None
+- Fixed a regression introduced with CrateDB 5.0.0 which can cause that some
```
Comment (mkleen) [inline docs/appendices/release-notes/5.4.3.rst:49]: The bug is not related to the table statistics/join-order but if a hash-join is nested on placed on the right right-hand-side.

Comment (mkleen) [reply docs/appendices/release-notes/5.4.3.rst:49]:
```
Fixed a regression introduced with CrateDB 5.0.0 which can cause an empty result
when a hash-join has multiple relations placed on the right-hand side.
```

Comment (seut) [reply docs/appendices/release-notes/5.4.3.rst:49]: I can not validate the issue from a SQL perspective by forcing a hash-join nested on the right side.
Example:
```
create table doc.t1(a int, b int);
create table doc.t2(c int, d int);
create table doc.t3(e int, f int);

insert into doc.t1(a,b) values(1,2);
insert into doc.t2(c,d) values (1,3),(5,6);
insert into doc.t3(e,f) values (3,2);

refresh table t1, t2, t3;
```

Note: NO `ANALYZE` is triggered.

Forcing a hash-join nested on the right side using sub-selects:
```
cr> explain SELECT t13.e FROM t2 JOIN (SELECT * FROM t1 JOIN t3 ON t1.b = t3.f) t13 ON t13.a = t2.c WHERE t2.d = t13.e;                                                                                                                                  
+-------------------------------------------+
| EXPLAIN                                   |
+-------------------------------------------+
| Eval[e]                                   |
|   └ HashJoin[((a = c) AND (d = e))]       |
|     ├ Collect[doc.t2 | [c, d] | true]     |
|     └ Rename[a, b, e, f] AS t13           |
|       └ HashJoin[(b = f)]                 |
|         ├ Collect[doc.t1 | [a, b] | true] |
|         └ Collect[doc.t3 | [e, f] | true] |
+-------------------------------------------+
EXPLAIN 1 row in set (0.004 sec)

cr> SELECT t13.e FROM t2 JOIN (SELECT * FROM t1 JOIN t3 ON t1.b = t3.f) t13 ON t13.a = t2.c WHERE t2.d = t13.e;                                                                                                                                          
+---+
| e |
+---+
| 3 |
+---+
SELECT 1 row in set (0.006 sec)
```

I agree that theoretically the issue is not related to join re-ordering but to unordered relation names (which is not deterministic but seems to happen for sure during join re-ordering).

Comment (mkleen) [reply docs/appendices/release-notes/5.4.3.rst:49]: I just flipped the join conditions.

Comment (seut) [reply docs/appendices/release-notes/5.4.3.rst:49]: Additionally, I think the issue can theoretically also occur with hash-joins nested on the left side due to wrong relation name ordering.

Comment (seut) [reply docs/appendices/release-notes/5.4.3.rst:49]: > Try:
> 
> ```
> cr> SELECT t13.e FROM t2 JOIN (SELECT * FROM t1 JOIN t3 ON t1.b = t3.f) t13 ON t2.d = t13.e AND t13.a = t2.c;
> +---+
> | e |
> +---+
> +---+
> ```

I cannot verify this locally, neither with 5.3.4 nor 5.4.0, I get valid results. What do I miss?

Comment (mkleen) [reply docs/appendices/release-notes/5.4.3.rst:49]: Sorry, that works.

Comment (mkleen) [reply docs/appendices/release-notes/5.4.3.rst:49]: Ignore the last comments.

Comment (mkleen) [reply docs/appendices/release-notes/5.4.3.rst:49]: I am also ok with the original note.

**Review by mkleen — APPROVED** [review]
Looks great, thank you!
