### PR TITLE
Route `sys.allocations` to the master node to get correct decisions

### LINKED ISSUE #16730: Query to `sys.allocations` has different output depending on the node
### CrateDB version

5.7.3

### CrateDB setup information

```json
  "hardware_specs": {
    "cpus_per_node": 4,
    "disk_size_per_node_bytes": 1099511627776,
    "disk_type": "standard",
    "disks_per_node": 1,
    "heap_size_bytes": 3758096384,
    "memory_per_node_bytes": 15032385536
```

### Problem description

We noticed a `low_watermark` notification and the Cluster status switched to `YELLOW`.  While investigating this we noticed that the query:

```sql
select * from sys.allocations where current_state <>'STARTED';
```

Returned different results/`explanantions`, depending to which node we have been connected to:



### Steps to Reproduce

Seemed somewhat constant.

### Actual Result

Node 0:

```text
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------+---------+--------------------------+---------+----------+------------+--------------+
| current_state | decisions                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | explanation                                                             | node_id | partition_ident          | primary | shard_id | table_name | table_schema |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------+---------+--------------------------+---------+----------+------------+--------------+
| UNASSIGNED    | [{"explanations": ["the node is above the low watermark cluster setting [cluster.routing.allocation.disk.watermark.low=89%], using more disk space than the maximum allowed [89.0%], actual free: [8.871316380990377%]"], "node_id": "Kd-NKyuLTkae3YLNTqiGFg", "node_name": "data-hot-1"}, {"explanations": ["a copy of this shard is already allocated to this node [[overview..partitioned.xxxx.04732dpi6srj8c1o60o30c1g][0], node[gdJHhcyJTOOFHmaYSgFMfA], [P], s[STARTED], a[id=XUH6QpyFSqy4rG6dplaXhg]]", "the node is above the low watermark cluster setting [cluster.routing.allocation.disk.watermark.low=89%], using more disk space than the maximum allowed [89.0%], actual free: [10.418274131943388%]", "there are too many copies of the shard allocated to nodes with attribute [zone], there are [2] total configured shard copies for this shard id and [5] total attribute values, expected the allocated shard count per attribute [2] to be less than or equal to the upper bound of the required number of shards per attribute [1]"], "node_id": "gdJHhcyJTOOFHmaYSgFMfA", "node_name": "data-hot-0"}, {"explanations": ["the node is above the low watermark cluster setting [cluster.routing.allocation.disk.watermark.low=89%], using more disk space than the maximum allowed [89.0%], actual free: [9.164740705115292%]"], "node_id": "lVG4-sP3Sn-iwJy_cs07yA", "node_name": "data-hot-2"}]     | cannot allocate because allocation is not permitted to any of the nodes | NULL    | 04732dpi6srj8c1o60o30c1g | FALSE   |        0 | metrics    | overview     |
| UNASSIGNED    | [{"explanations": ["the node is above the low watermark cluster setting [cluster.routing.allocation.disk.watermark.low=89%], using more disk space than the maximum allowed [89.0%], actual free: [8.871316380990377%]"], "node_id": "Kd-NKyuLTkae3YLNTqiGFg", "node_name": "data-hot-1"}, {"explanations": ["a copy of this shard is already allocated to this node [[xxxx..partitioned.xxxx.04732dpi6srj8c1o60o30c1g][0], node[gdJHhcyJTOOFHmaYSgFMfA], [P], s[STARTED], a[id=wiR8Qve6S2u_DJCb_bHQTw]]", "the node is above the low watermark cluster setting [cluster.routing.allocation.disk.watermark.low=89%], using more disk space than the maximum allowed [89.0%], actual free: [10.418274131943388%]", "there are too many copies of the shard allocated to nodes with attribute [zone], there are [2] total configured shard copies for this shard id and [5] total attribute values, expected the allocated shard count per attribute [2] to be less than or equal to the upper bound of the required number of shards per attribute [1]"], "node_id": "gdJHhcyJTOOFHmaYSgFMfA", "node_name": "data-hot-0"}, {"explanations": ["the node is above the low watermark cluster setting [cluster.routing.allocation.disk.watermark.low=89%], using more disk space than the maximum allowed [89.0%], actual free: [9.164740705115292%]"], "node_id": "lVG4-sP3Sn-iwJy_cs07yA", "node_name": "data-hot-2"}] | cannot allocate because allocation is not permitted to any of the nodes | NULL    | 04732dpi6srj8c1o60o30c1g | FALSE   |        0 | metrics    | xxxx |
+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------+---------+--------------------------+---------+----------+------------+--------------+

```

---
Node 2 (similar result on node 1):

```text
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------+--------------------------+---------+----------+------------+--------------+
| current_state | decisions                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | explanation            | node_id | partition_ident          | primary | shard_id | table_name | table_schema |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------+--------------------------+---------+----------+------------+--------------+
| UNASSIGNED    | [{"explanations": null, "node_id": "lVG4-sP3Sn-iwJy_cs07yA", "node_name": "data-hot-2"}, {"explanations": null, "node_id": "Kd-NKyuLTkae3YLNTqiGFg", "node_name": "data-hot-1"}, {"explanations": ["a copy of this shard is already allocated to this node [[xxxxx..partitioned.metrics.04732dpi6srj8c1o60o30c1g][0], node[gdJHhcyJTOOFHmaYSgFMfA], [P], s[STARTED], a[id=wiR8Qve6S2u_DJCb_bHQTw]]", "there are too many copies of the shard allocated to nodes with attribute [zone], there are [2] total configured shard copies for this shard id and [5] total attribute values, expected the allocated shard count per attribute [2] to be less than or equal to the upper bound of the required number of shards per attribute [1]"], "node_id": "gdJHhcyJTOOFHmaYSgFMfA", "node_name": "data-hot-0"}] | can allocate the shard | NULL    | 04732dpi6srj8c1o60o30c1g | FALSE   |        0 | metrics    | xxx |
| UNASSIGNED    | [{"explanations": null, "node_id": "lVG4-sP3Sn-iwJy_cs07yA", "node_name": "data-hot-2"}, {"explanations": null, "node_id": "Kd-NKyuLTkae3YLNTqiGFg", "node_name": "data-hot-1"}, {"explanations": ["a copy of this shard is already allocated to this node [[overview..partitioned.xxxx.04732dpi6srj8c1o60o30c1g][0], node[gdJHhcyJTOOFHmaYSgFMfA], [P], s[STARTED], a[id=XUH6QpyFSqy4rG6dplaXhg]]", "there are too many copies of the shard allocated to nodes with attribute [zone], there are [2] total configured shard copies for this shard id and [5] total attribute values, expected the allocated shard count per attribute [2] to be less than or equal to the upper bound of the required number of shards per attribute [1]"], "node_id": "gdJHhcyJTOOFHmaYSgFMfA", "node_name": "data-hot-0"}]     | can allocate the shard | NULL    | 04732dpi6srj8c1o60o30c1g | FALSE   |        0 | metrics    | overview     |
+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------+---------+--------------------------+---------+----------+------------+--------------+

``` 

### Expected Result

All nodes show the same consistent output. The `explanation` from the node with the _active_  low watermark, was much more useful than from the other node.

### PR DESCRIPTION
**Pull request by seut**
Only the master node is collecting all cluster information values like disk usages of all nodes.
Thus, only the master node can give the correct allocation decisions, e.g. when a node reaches disk watermark thresholds.

Fixes #16730.

### CODE REVIEW

**Comment by seut** [comment]
A unit test is maybe better, will push one.

**Comment by seut** [comment]
I've added a unit test, see https://github.com/crate/crate/pull/16765/commits/9466a859b155ccb4e36d57ff7489326faad274fd.

I'd drop the integration test, or do you see value in keeping it?

**Review by matriv — APPROVED** [review]
LGTM, nice!
imho, I would just keep the unit test.
Since `localNodeId` is set to `d1` it should be deterministic, that the test would pick `d1` without the fix, correct? (UPD: verified, that this is the case).

File: server/src/main/java/io/crate/metadata/sys/SysAllocationsTableInfo.java [hunk 1]
```diff
@@ -55,5 +56,6 @@ public class SysAllocationsTableInfo {
             ColumnIdent.of("partition_ident"),
             ColumnIdent.of("shard_id")
         )
+        .withRouting((state, routingProvider, sessionSettings) -> Routing.forTableOnMasterNode(IDENT, state.nodes()))
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/metadata/sys/SysAllocationsTableInfo.java:59]:
```suggestion
        .withRouting((state, routingProvider, sessionSettings) -> Routing.forTableOnSingleNode(IDENT, state.nodes().getMasterNodeId()))
```

Doesn't seem worth an extra method?

**Review by mfussenegger — APPROVED** [review]
> I'd drop the integration test

+1
