### PR TITLE
Fixes too early consumer processing on the IncrementPageBucketReceiver

### LINKED ISSUE #18688: QUERY circuit breaker memory is not released when LIMIT 0 is used on top of aggregations
### CrateDB version

5.10.13

### CrateDB setup information

Number of nodes: 3

### Problem description

When using a `LIMIT 0` on top of aggregations running in a multi-node cluster (distributed aggregations), the accounted memory on the `QUERY` circuit breaker is not released when the query is done. 
By this, the accounted memory will constantly increase and can only be reset by a node restart.

### Steps to Reproduce

1. Run a cluster with at least 2 nodes, ensure no other queries are running (Cloud Setup will run queries, so the breaker may not have 0 bytes usage).
2. `CREATE TABLE t1 (name TEXT, x INT);`
3. `INSERT INTO t1 (name, x) VALUES ('Apple', 1), ('Apple', 2), ('Apple', 3);`
4. `REFRESH TABLE t1;`
5. `SELECT name, MAX(x) FROM t1 GROUP BY name LIMIT 0;`

Check the `used` value of the `QUERY` circuit breaker using JMX, it is not reset to 0 even that no queries are running. Or if other queries are running meanwhile, the breaker `used` may not be 0, but will constantly increase the more often the problematic query is run.

### Actual Result

Accounted memory on the `QUERY` circuit breaker is constantly increasing.

### Expected Result

Accounted memory on the `QUERY` circuit breaker is released once the query is done.

### PR DESCRIPTION
**Pull request by seut**
A given consumer must only be called once some buckets are set, otherwise some callbacks will be triggered too early when the consumers finishes immediately.
This results e.g. in the RamAccounting callbacks being released before some other components add accounted memory on it resulting in accounted memory which will never be released again.

The 2nd commit fixes the error handling in cases when an error is thrown while consuming the first page/bucket. This fixes cases where a query may get stuck and never respond. Came across this while working in the first issue, looks like a valid issue.

Fixes #18688.

### CODE REVIEW

File: server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java [hunk 1]
```diff
@@ -76,8 +75,12 @@ public IncrementalPageBucketReceiver(Collector<Row, T, Iterable<Row>> collector,
...
 
     private void processRows(Bucket rows) {
-        for (Row row : rows) {
-            accumulator.accept(state, row);
+        try {
+            for (Row row : rows) {
+                accumulator.accept(state, row);
+            }
+        } catch (Exception e) {
+            processingFuture.completeExceptionally(e);
```
Comment (BaurzhanSakhariev) [inline server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java:87]: Quick question - doesn't `test_listener_doesnt_need_more_when_processRows_throws` cover a case when accumulator throws? `public BiConsumer<Object, Row> accumulator()` throws a CBE.
 
I somehow thought that  an exception in 
`CompletableFuture.runAsync(() -> processRows(rows), executor);` just leads to `currentlyAccumulating` being completed exceptionally and later on handled in error handling branch of
`currentlyAccumulating = currentlyAccumulating.whenComplete((r, t)`
  
I remember adding a debug flag like `mustThrow` to `processRows` and letting first run throw and second don't - this setup only led to "good" failures with CBE-s. And setup with first run not throwing and throwing in `currentlyAccumulating.whenComplete` led to some issues with incomplete results - but it was quite some time ago, maybe I'm missing something

File: server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java [hunk 2]
```diff
@@ -142,7 +139,6 @@ public void consumeRows() {
 
     @Override
     public void kill(@NotNull Throwable t) {
-        lazyBatchIterator.kill(t);
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java:145]: Could this instead set `killed = t` and have a check in `processRows` for that?
If I understand the logic right, only completing the future would trigger error propagation to the client, but if `processRows` is active, the operation would continue running

**Review by mfussenegger — APPROVED** [review]

File: server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java (hunk 1 above)
Comment (seut) [reply server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java:87]: Yes right, `test_listener_doesnt_need_more_when_processRows_throws` covers also a case where the accumulator throws, but not on the first page/bucket (an empty bucket is used) but on the follow up calls. So it tests the 2nd code path.

> and later on handled in error handling branch of

What if there is no "later on" as only one page/bucket is set.?

Comment (BaurzhanSakhariev) [reply server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java:87]: Right, thanks for clarifying

File: server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java (hunk 2 above)
Comment (seut) [reply server/src/main/java/io/crate/execution/IncrementalPageBucketReceiver.java:145]: Done with https://github.com/crate/crate/pull/18723/commits/315d7976a6cd0dc3e8acb13e126e191ba36af0bb.
