### PR TITLE
Fix trimUnsafeCommits for indices created before 3.2

### LINKED ISSUE #11756: Big partitioned table isn't recovering on 4.6.3 on k8s cluster.
### CrateDB version

4.6.3

### CrateDB setup information

3 node crate 4.6.3 cluster on k8s with 6g heap size and a table with 900 million records partitioned per week with 12 shards and 1 replica. 

### Steps to Reproduce

I upgraded from 4.6.1 to 4.6.3 by bringing the 3 pods down. Then adjusting the yaml and bringing the cluster up again. That went fine, all is starting and most tables in db are recovering fine. But the big table isn't. The table is partly recovering. The oldest partitions are stated critical and won't recovering, while others turn green. Crate is saying the total of the amount of records in the table are 760 million instead of the 910 million it should have. I don't understand, because there must be at least 1 replica on one of the nodes, but it seams to be lost because its staying critical. The only thing I can do is restore the whole table from a snapshot now. This is happend me before also on 4.6.1. So I think somehow big tables are hard to recover. Didn't have problem this on older cratedb versions.

### Expected Result

I expect it to rebuild the table fine. because it was green before the cluster was downnscaled to 0 and there was a replica in place. 

### Actual Result

Not sure where to find the logs.

### PR DESCRIPTION
**Pull request by seut**
## Summary of the changes / Why this improves CrateDB

Backport of https://github.com/elastic/elasticsearch/pull/57187

Fixes #11756.

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

File: server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java [hunk 1]
```diff
@@ -248,6 +249,7 @@ public void testPrepareIndexForPeerRecovery() throws Exception {
         }
         assertThat(replica.recoveryState().getTranslog().recoveredOperations(), equalTo(0));
         assertThat(replica.getLastKnownGlobalCheckpoint(), equalTo(UNASSIGNED_SEQ_NO));
+        assertThat(replica.recoveryState().getStage(), equalTo(RecoveryState.Stage.TRANSLOG));
```
Comment (seut) [inline server/src/test/java/org/elasticsearch/indices/recovery/PeerRecoveryTargetServiceTests.java:252]: This assertion will fail without the fix. And by always using a globalCheckpoint < maxSeqNo, the test will always fail and not occasionally only (like it does on the original commit).

**Comment by seut** [comment]
Unfortunately this change causes a different flakiness on `testRecoverFromLocalTranslog`, will investigate first.

**Comment by seut** [comment]
I've commented on the wrong PR 🤦 , this change is fine and does not introduce other failures.

**Review by mfussenegger — APPROVED** [review]
