### PR TITLE
Don't discard additional implicit join conditions in nested joins

### LINKED ISSUE #13808: Using nested joins with explicit and implicit join conditions results in wrong plan/wrong results
### CrateDB version

5.2.4 (and master/nightly) but also older version are affected

### CrateDB setup information

Single node development setup

### Problem description

When using nested joins with join conditions and an implicit join condition inside the `WHERE` clause, this join condition will be lost if it reference a different relation of a parents join pair than the explicit join condition.

### Steps to Reproduce

1. Create 3 tables:
```
CREATE TABLE j1 (x INT);
CREATE TABLE j2 (y INT);
CREATE TABLE j3 (z INT);
```
2. 1st query variant (this works correctly on CrateDB <= 5.2.3):
```
EXPLAIN SELECT * FROM j1 JOIN j2 ON j1.x = j2.y JOIN j3 ON j1.x = j3.z WHERE j2.y = j3.z;
```
3. 2nd query variant (this results in a wrong plan even on CrateDB <= 5.2.3):
```
EXPLAIN SELECT * FROM j1 JOIN j2 ON j1.x = j2.y JOIN j3 ON j2.y = j3.z WHERE j1.x = j3.z;
```

### Actual Result

1st query variant on CrateDB 5.2.3, this is correct as both conditions on the 2nd join are applied:
```
+-------------------------------------+
| EXPLAIN                             |
+-------------------------------------+
| HashJoin[((x = z) AND (y = z))]     |
|   ├ HashJoin[(x = y)]               |
|   │  ├ Collect[doc.j1 | [x] | true] |
|   │  └ Collect[doc.j2 | [y] | true] |
|   └ Collect[doc.j3 | [z] | true]    |
+-------------------------------------+
```

1st query variant on CrateDB 5.2.4/master, this is wrong, the condition/filter declared inside the `WHERE` clause is lost 
(related change https://github.com/crate/crate/commit/e9624a9dcd64c40e8fd26b8285e187394e289adf):
```
+-------------------------------------+
| EXPLAIN                             |
+-------------------------------------+
| HashJoin[(x = z)]                   |
|   ├ HashJoin[(x = y)]               |
|   │  ├ Collect[doc.j1 | [x] | true] |
|   │  └ Collect[doc.j2 | [y] | true] |
|   └ Collect[doc.j3 | [z] | true]    |
+-------------------------------------+
```

2nd query variant actual results (any CrateDB version). This is wrong as the condition/filter used inside the `WHERE` clause is lost:
```
+-------------------------------------+
| EXPLAIN                             |
+-------------------------------------+
| HashJoin[(x = z)]                   |
|   ├ HashJoin[(x = y)]               |
|   │  ├ Collect[doc.j1 | [x] | true] |
|   │  └ Collect[doc.j2 | [y] | true] |
|   └ Collect[doc.j3 | [z] | true]    |
+-------------------------------------+
```

### Expected Result

1st query:
```
+-------------------------------------+
| EXPLAIN                             |
+-------------------------------------+
| HashJoin[((x = z) AND (y = z))]     |
|   ├ HashJoin[(x = y)]               |
|   │  ├ Collect[doc.j1 | [x] | true] |
|   │  └ Collect[doc.j2 | [y] | true] |
|   └ Collect[doc.j3 | [z] | true]    |
+-------------------------------------+
```

2nd query:
```
+-------------------------------------+
| EXPLAIN                             |
+-------------------------------------+
| HashJoin[((y = z) AND (x = z))]     |
|   ├ HashJoin[(x = y)]               |
|   │  ├ Collect[doc.j1 | [x] | true] |
|   │  └ Collect[doc.j2 | [y] | true] |
|   └ Collect[doc.j3 | [z] | true]    |
+-------------------------------------+

```

### PR DESCRIPTION
**Pull request by seut**
## Summary of the changes / Why this improves CrateDB

Any JOIN clause will be split by the planner into join pairs containing only 2 relations even if on side of the join reference a parent join (because join pairs are based on relations). Any WHERE clause filter referencing to a join and such results in an additional join condition will either be added to an existing JoinPair or a new one will be created depending on the referenced relations.
This new join pair condition must be taken into account when building the join conditions.
Example:

```
t1 JOIN t2 ON t1.x = t2.y JOIN t3 ON t1.x = t3.z WHERE t2.y = t3.z
-> JoinPair(t1, t2)	<- 1st JOIN
-> JoinPair(t1, t3)     <- 2nd JOIN
-> JoinPair(t2, t3)     <- additional joinPair, condition must be added to the 2nd JOIN
```

Fixes #13808.

## Checklist

 - [x] Added an entry in `CHANGES.txt` for user facing changes
 - [x] Updated documentation & `sql_features` table for user facing changes
 - [x] Touched code is covered by tests
 - [x] [CLA](https://crate.io/community/contribute/cla/) is signed
 - [x] This does not contain breaking changes, or if it does:
    - It is released within a major release
    - It is recorded in ``CHANGES.txt``
    - It was marked as deprecated in an earlier release if possible
    - You've thought about the consequences and other components are adapted
      (E.g. AdminUI)

### CODE REVIEW

File: server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java [hunk 1]
```diff
@@ -192,13 +192,29 @@ private static LogicalPlan joinWithNext(Function<AnalyzedRelation, LogicalPlan>
...
-            condition = joinPair.condition();
+            if (joinPair.condition() != null) {
+                conditions.add(joinPair.condition());
+            }
+            // There could be additional joinPairs that are not directly connected to the current joinPair,
+            // when there are WHERE clauses referencing to multiple relations of a previous join which was converted
+            // into a joinPair by JoinOperations.convertImplicitJoinConditionsToJoinPairs(...)
+            // Example:
+            //  t1. JOIN t2 ON t1.x = t2.y JOIN t3 ON t1.x = t3.z WHERE t2.y = t3.z
+            //  -> JoinPair(t1, t2)     <- 1st JOIN
```
Comment (BaurzhanSakhariev) [inline server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java:208]: Just curious what happens if we try to add same pair implicitly and explicitly:
```
SELECT * FROM j1 
  JOIN j2 ON j1.x = j2.y 
  JOIN j3 ON j1.x = j2.y AND j2.y = j3.z 
WHERE j2.y = j3.z
```
I guess (j2,j3) will be handled twice? If if it's the case, don't think it's a problem(?), we would just check same condition twice.

Comment (seut) [reply server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java:208]: @BaurzhanSakhariev 
Good point, but this isn't inside the scope of this PR as this happens already if the same explicit condition is added twice.

```
cr> EXPLAIN SELECT * FROM j1  JOIN j2 ON j1.x = j2.y AND j1.x = j2.y 
+----------------------------------+
| EXPLAIN                          |
+----------------------------------+
| HashJoin[((x = y) AND (x = y))]  |
|   ├ Collect[doc.j1 | [x] | true] |
|   └ Collect[doc.j2 | [y] | true] |
+----------------------------------+
```


And yes, performance wise we should detect any duplication and remove it to avoid useless evaluation on the same function. I've created an issue for this #13810, but I'm not sure how important this is/how big the performance impact is.

Comment (BaurzhanSakhariev) [reply server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java:208]: UPD: Same pair case can be even trickier, 
implicit can be `ON ... AND j2.y = j3.z ` and implicit same thing but swapped: `WHERE j3.z = j2.y`

I guess we will have 2 pairs (j2,j3) (j3,j2) - but again I don't think it's a big problem

Comment (BaurzhanSakhariev) [reply server/src/main/java/io/crate/planner/operators/JoinPlanBuilder.java:208]: >how big the performance impact is.

I agree, don't think it's a big deal

**Review by BaurzhanSakhariev — APPROVED** [review]
👍
