### PR TITLE
Fix new column collection to not contain duplicates

### LINKED ISSUE #17691: `Limit of total columns [1000] exceeded` on newly created table when inserting >1000 fields, but not columns
### CrateDB version

Nightly build 03f728c

### CrateDB setup information

Docker standard.

```
docker run --rm -it --name=cratedb \
  --publish=4200:4200 --publish=5432:5432 \
  --env=CRATE_HEAP_SIZE=2g crate/crate:nightly \
  -Cdiscovery.type=single-node
```

### Problem description

The symptom is that when using `OBJECT(DYNAMIC)` and inserting arrays including objects, each small [^1], but totalling into more than 1000 fields, like 4 fields * 250 objects, into a newly created table, the venerable column limit error is raised.

    Limit of total columns [1000] in table [doc.total1000] exceeded

When the table has been populated already, there is no problem at all.

#### Source
https://gist.github.com/amotl/17e8c03701a8e1803d6dff2429098e74

#### Usage
```
wget https://gist.githubusercontent.com/amotl/17e8c03701a8e1803d6dff2429098e74/raw/6edaf7cf4b9d174a6eb325e4a8307dfb8271c94f/bug1000.py
```
```
uv run bug1000.py
```

### Actual Result

```python
sqlalchemy.exc.ProgrammingError: (crate.client.exceptions.ProgrammingError) 
SQLParseException[Limit of total columns [1000] in table [doc.total1000] exceeded]
[SQL: INSERT INTO total1000 (data) VALUES (?)]
[parameters: ({'thing': [{'time': 1743107159471, 'stmt': "SELECT * FROM sys.jobs_log WHERE stmt NOT LIKE '%  -- ctk' OFFSET 591  -- ctk", 'duration': 4, 'username': ... (37211 characters truncated) ... {'time': 1743107159471, 'stmt': "SELECT * FROM sys.jobs_log WHERE stmt NOT LIKE '%  -- ctk' OFFSET 591  -- ctk", 'duration': 4, 'username': 'crate'}]},)]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

### Expected Result

The insert operation works like before.

Thanks. 🙏

[^1]:
     ```json
     item = {
       "time": 1743107159471,
       "stmt": "SELECT * FROM sys.jobs_log WHERE stmt NOT LIKE '%  -- ctk' OFFSET 591  -- ctk",
       "duration": 4,
       "username": "crate"
     }
     ```

### PR DESCRIPTION
**Pull request by seut**
Duplicated new columns weren't a real issue besides memory consumption until the field limit detection on dynamically added columns was fixed by https://github.com/crate/crate/commit/ea6fa68af2.

Fixes #17691.

### CODE REVIEW

**Review by BaurzhanSakhariev — APPROVED** [review]

File: server/src/main/java/io/crate/execution/dml/Indexer.java [hunk 1]
```diff
@@ -679,7 +680,7 @@ private static void addGeneratedToVerify(Map<ColumnIdent, ColumnConstraint> colu
      * Looks for new columns in the values of the given IndexItem and returns them.
      */
     public List<Reference> collectSchemaUpdates(IndexItem item) throws IOException {
-        ArrayList<Reference> newColumns = new ArrayList<>();
+        HashSet<Reference> newColumns = new HashSet<>();
```
Comment (mfussenegger) [inline server/src/main/java/io/crate/execution/dml/Indexer.java:683]: I think we have some tests that assert certain position/ordinals - if we use a set here that may become undeterministic and flaky. 

Probably worth giving tests a few iterations to see if all is good - and if not, use a LinkedHashSet?

Comment (seut) [reply server/src/main/java/io/crate/execution/dml/Indexer.java:683]: Good point, thx. Will check.
